.travis.yml
Makefile
demo/main.cpp

We now build and test coverage/sanitize/release builds on Linux & macOS and debug/release builds on Windows.
Release builds now use NDEBUG which helps by catching unused variables on all platforms.

Improve Travis CI coverage

---

tools/objparser.cpp

Just made a loop shorter and more readable

Simplified loop in objparser.cpp

---

.travis.yml
tools/gltfpack.cpp

This will make sure we don't regress on any platform in the future.

Add gltfpack to Travis-CI

---

tools/gltfpack.cpp

We use a heuristic for when constant tracks aren't useful: if *all*
tracks within the file that target the node path have the same value as
the base, this is indicative of the fact that we won't need this data.
This is not definitive - if glTF file *only* stores animation data, you
might want to load this file over some other file with mesh data, and
actually pose the mesh accordingly - but this usecase is unlikely.
This behavior can be disabled using -ac switch which will preserve
constant animation tracks.

gltfpack: Implement removal of constant animation tracks

---

CMakeLists.txt

Added missing source file (for meshopt_setAllocator).

Added src/allocator.cpp to SOURCES

---

tools/gltfpack.cpp

We now make sure that all influences with 0 weight do not carry the
index and other influences are sorted by the index.
Sorting by the index instead of the weight helps compression; this
change makes the typical skinned meshes ~0.3% smaller. The gain on
skinning data is around 6%, for example on jrat.glb we get:
no sort: 24895 bytes
JOINTS: compressed 7970 bytes (2.6 bits), raw 99044 bytes (32 bits)
WEIGHTS: compressed 16925 bytes (5.5 bits), raw 99044 bytes (32 bits)
sort by joint: 23336 bytes
JOINTS: compressed 6252 bytes (2.0 bits), raw 99044 bytes (32 bits)
WEIGHTS: compressed 17084 bytes (5.5 bits), raw 99044 bytes (32 bits)

gltfpack: Sort bone influences by bone index

---

tools/gltfpack.cpp

We now analyze the maximum delta for morph positions and use 8-bit
storage if possible. This often results in us saving a noticeable amount
of memory/decoded size; it doesn't affect compressed size much.
For example, on one test asset with many morph targets, we get:
original size: 11 485 228 bytes
before this change: 5 495 424 bytes uncompressed, 1 015 568 bytes compressed
after this change: 3 866 552 bytes uncompressed, 974 893 bytes compressed
Note that this results in base position stream using 16-bit integer
storage and morph delta stream using 8-bit integer storage; this works
just fine in BabylonJS but requires ThreeJS r111 to decode correctly.

gltfpack: Use 8-bit morph target deltas when possible

---

extern/cgltf.h
gltf/gltfpack.cpp
gltf/material.cpp
gltf/write.cpp

Spec: https://github.com/KhronosGroup/glTF/pull/1756
Based on cgltf PR: https://github.com/jkuhlmann/cgltf/pull/107

gltfpack: Implement support for KHR_materials_clearcoat

---

.github/workflows/build.yml

This version should support new SIMD encoding.

Update CI to use Node 14.6

---

gltf/gltfpack.cpp

A new option, -r file, can be used to output a JSON report for the
processing of the scene.
The report contains summary scene information (counts of various
objects), render complexity (number of draw calls and triangles) and
data sizes (JSON/binary sizes plus a breakdown of buffer data).
Unlike -v/-vv which is purely informational and can change at any point
in time, the schema for -r should be reasonably stable from version to
version.
Fixes #162.

gltfpack: Implement support for JSON report output

---

extern/cgltf.h
gltf/gltfpack.cpp
gltf/image.cpp
gltf/material.cpp
gltf/write.cpp

This includes cgltf plumbing that has been submitted upstream in https://github.com/jkuhlmann/cgltf/pull/128

gltfpack: Implement support for KHR_materials_sheen

---

.github/workflows/build.yml

A recently introduced Box With Spaces isn't xargs-friendly.

gltfpack: Fix CI build for files with spaces

---

gltf/mesh.cpp

Fix for issue https://github.com/zeux/meshoptimizer/issues/315

Fix merging multiple meshes that have different flip face winding

---

gltf/image.cpp

https://en.wikipedia.org/wiki/Portable_Network_Graphics#File_header
8 signature
8 IHDR start
4(width) + 4(height) + 1 bit depth
26th byte is color type (index 25)

The PNG image type should be at offset 25 - not 27

---

js/meshopt_decoder.js
js/meshopt_decoder.module.js

SIMD support is now widely available in production browsers and it works
well.

js: Remove experimental SIMD log from decoder

---

extern/cgltf.h

This consists of the latest updates to cgltf plus
https://github.com/jkuhlmann/cgltf/pull/157 -- together these should
allow us to process files that are 2GB or larger using 64-bit native
binaries. JS binaries are going to be limited by 4GB Wasm heap as
before.

gltfpack: Update cgltf to support 2GB+ glTF inputs

---

README.md
gltf/README.md

Add links to EXT_meshopt_compression extension

---

.github/workflows/release.yml
gltf/gltfpack.cpp
gltf/gltfpack.h
gltf/image.cpp
gltf/write.cpp

This sets the stage for parallel texture compression

gltfpack: Cleanup Basis integration

---

gltf/basisenc.cpp
gltf/basislib.cpp

This requires associated changes from zeux/basis_universal @ gltfpack.

gltfpack: Update to Basis 1.16

---

extern/cgltf.h
gltf/gltfpack.cpp
gltf/material.cpp
gltf/write.cpp

This is using cgltf patch from upstream PR https://github.com/jkuhlmann/cgltf/pull/205

gltfpack: Implement support for KHR_materials_anisotropy

---

gltf/README.md

`-vpf` is important enough to show in the overview documentation.

gltf: Update README.md

---

README.md

Minor API change made the readme need a little update. Thanks for the awesome library!

add options to simplify example

---

.github/workflows/build.yml
.github/workflows/release.yml

Node.js 16 actions are deprecated

Update GitHub actions versions to switch to node.js 20

---

gltf/image.cpp

Some glTF files exported by non-compliant tool chains may use mimeType: image/png but use JPEG images. While these files are invalid, it would be helpful to make an effort to fix this as the mimeType information is fairly redundant.
This change uses image header patterns defined in glTF specification to override mime type even if it's defined based on the image contents; this is done in readImage so that all consumers (that are mime type dependent!) get the correct result.

gltfpack: Fixup image mime type between jpeg/png based on headers

---

.github/workflows/build.yml

This should better take advantage of the 4-core setup that GHA uses now.

Increase parallelism on GitHub Actions

---

USERS.md

Hello,
I wanted to link Wicked Engine as it is using meshoptimizer for the following tasks:
- optimization
- LOD generation
- meshlet generation
Thank you for working on meshoptimizer!

Added Wicked Engine to the engines list

---

src/spatialorder.cpp

Previously, we've used a three-pass radix sort to sort points or triangles by making a 30-bit Morton code, with 10 bits per axis.
For some dense meshes, this resulted in an order that was insufficiently precise at lower levels: positions that would fall into the same quantization bucket would get the same Morton code and may not be ordered properly.
Depending on the use case, this can regress various metrics, such as compression size (if spatial sorting is used to improve compression), or BVH quality or build performance (if spatial sorting is used as a starting order for a BVH builder).
This change expands the precision to 16 bits per axis, which gives us 48 bits total and requires 5 radix sort passes. As a result, sorting is ~50% more expensive (but still pretty fast).
In the future we …

spatialorder: Improve position precision for spatialSort

---

src/partition.cpp

Instead of using source cluster indices directly, we now fill a freshly allocated
buffer with the copy of cluster indices, removing the duplicates in the
process. This makes adjacency builds much faster with the existing code,
and allows further simplification in cases where used[] array was used
to filter out duplicates from the same cluster. This makes partitioning ~2x
faster overall on regular meshes.
This also allows easier first class support for spatial links... however, an initial
attempt at implementing those seems to mostly regress partitioning quality,
because for clusters with non perfectly circular shape, spatial adjacency can
end up picking up clusters that aren't directly adjacent; doing this at every
level progressively degrades DAG quality for meshes that, without this, …

partition: Deduplicate cluster indices before adjacency building
