- CMakeLists.txt
- Makefile
- demo/main.cpp
This will make sure codebase stays warning-clean.
> Use warnings-as-errors and high warning levels

- .travis.yml
We can now switch to language: cpp and don't need to setup CMake path
manually.
> Refactor Travis CI build scripts

- .travis.yml
- src/vertexcodec.cpp
Travis config had a typo that was causing sanitize builds to be
disabled.
> Enable sanitize configuration for clang builds

- .travis.yml
- Makefile
That way we can have both ARM and ARM64 code compiled in CI even if we
can't test it.
> Add armv7/aarch64 iOS builds to Travis OSX

- demo/main.cpp
- src/meshoptimizer.h
- src/simplifier.cpp
- tools/lodviewer.cpp
The default simplifier faithfully follows the topology and doesn't like
collapsing vertices in ways that violate topological consistency. It is
likely that we'll try to unlock some of the collapse options in the
future somehow, and/or recommend discarding and regenerating some
attributes via shadow IB, but that fundamentally limits the algorithm.
Additionally, the simplifier doesn't know how to collapse small regions
of the mesh other than faithfully following topology - which in some
cases is great but isn't always appropriate. It doesn't merge features
that are topologically disjoint because, again, it's topology-driven.
The new simplifier instead completely disregards topology, using an
out-of-core simplification foundation where the space is divided into
cells, and all vertices in a …
>  simplify: Introduce a second simplifier, simplifySloppy

- src/allocator.cpp
- src/meshoptimizer.h
meshopt_setAllocator can be used to override default allocation
callbacks (new/delete) with arbitrary functions with matching signature.
The callbacks are stored in global statics; to maintain independence
between individual translation units, the statics are declared in the
header file as templated class statics. They are instantiated in each
translation unit that uses meshopt_Allocator, and merged by linker into
a single symbol.
Note, this change also switches to stack order for deallocating blocks in
meshopt_Allocator to make it easier to implement custom allocators.
> Add support for custom allocators

- .travis.yml
- src/indexgenerator.cpp
- src/simplifier.cpp
codecov script is doing something incredibly weird that results in
meshoptimizer.h being split between src/meshoptimizer.h and
demo/../src/meshoptimizer.h. This results in misleading coverage
information.
Additionally, running gcov ourselves gives us an opportunity to fix
unreachable coverage lines using a simple sed script.
We also now limit coverage run to gcc since clang on Linux doesn't work
and gcov on OSX has somewhat different behavior.
> Rework coverage reporting to run gcov manually

- demo/main.cpp
- src/clusterizer.cpp
- src/meshoptimizer.h
Optimize meshopt_computeMeshletBounds by passing in pointer to meshlet instead of by value (636 bytes)
> Optimize meshopt_computeMeshletBounds

- demo/main.cpp
- src/simplifier.cpp
Instead of linear interpolation, we now use three point interpolation
search. On many meshes it performs roughly the same, but on some meshes
it does fewer passes by being able to adapt to the actual curve better.
On a full test mesh collection (5 GB of .obj files), running three
simplification attempts for each mesh with factors 0.5, 0.1 and 0.01
requires 2400 passes (14 seconds) with old method and 2000 passes (13
seconds) with new method.
> simplifySloppy: Use three point interpolation search

- README.md
- demo/main.cpp
- src/indexcodec.cpp
- src/meshoptimizer.h
- src/stripifier.cpp
This change adds strip stitching using degenerate triangles instead of
restart indices. This is less memory efficient, but it can improve GPU
performance on some systems since restart indices serialize
index processing.
On nyra.obj, restart indices result in 57% index data compared to
triangle lists, whereas degenerate indices result in 62%, so index data
is 1.1x bigger.
meshopt_stripifyBound always assumes worst case so that we don't need to
pass an extra parameter.
> stripify: Add support for degenerate triangles

- tools/fast_obj.h
- tools/gltfpack.cpp
The goal for gltfpack is to be able to produce efficient .gltf/.glb
assets starting from a .gltf input, but it's very convenient to be able
to test .obj files as well.
Additionally, if we can support .obj files, we can completely remove
meshencoder/optmesh in favor of that, and maintain the ability to work
with .obj inputs.
Our .obj parser doesn't support material libraries, so this change adds
fast_obj.h that does (and also is slightly faster than our parser), and
adds support for .obj meshes to gltfpack.
> gltfpack: Implement .obj/.mtl parsing

- demo/index.html
- tools/gltfpack.cpp
This change adds animation support to gltfpack; we now support TRS tracks for nodes with linear interpolation.
All animation tracks are resampled at a fixed frequency which allows us to share the input accessor; additionally constant tracks are folded into a singleton input/output.
There's currently no quantization/compression involved; 16-bit quaternion quantization reduces the size substantially but it doesn't look like Three.JS or Babylon.JS support it right now :(
> gltfpack: Implement animation support

- tools/gltfpack.cpp
This PR fixes animation truncation during resampling (e.g. sampling 0.1 second animation at 15 Hz would drop the last frame or two), changes the default resampling rate to less aggressive 30 Hz and adds (disabled) rotation track compression that results in substantial size gains but requires fixes in Three.JS/Babylon.JS to work.
> gltfpack: Animation fixes and improvements

- demo/GLTFLoader.js
- tools/gltfpack.cpp
Since there.js now supports quantized quaternion rotations, we can
enable rotation track quantization; also remove compression mode from
GLTF file as it's redundant in presence of the first byte, and start
compressing animation data for further benefits.
> gltfpack: Enable animation compression 

- tools/gltfpack.cpp
This PR adds support for custom normal quantization, unit-length normals and cleans up the code a bit.
Custom normal quantization is helpful because normals/tangents are hard to compress due to high entropy, and often 5 or 6 bits are enough.
Unit-length normal support is valuable for renderers that don't normalize (and presumably don't scale!) normals. Unit-length normals are slightly less precise and larger, so this option is off by default.
> gltfpack: Quantization improvements

- tools/gltfpack.cpp
After this change, each vertex attribute stream type gets a separate
buffer view - which has neutral effect on compression but allows us to
use different compression types more easily and makes for simple
accounting.
This makes it easy to display stats for each vertex/keyframe component
separately, which allows us to evaluate compression efficiency.
> gltfpack: Implement detailed statistics for vertex/keyframe streams

- tools/gltfpack.cpp
This change implements a flag, -kn, that restricts the mesh merging and
node tree simplification assuming that nodes with a name are important
to preserve and can be manipulated externally.
This amounts to a few things:
- We keep named nodes around even if they are not otherwise referenced.
This can be important for preserving attachment points for characters
for example.
- We keep meshes attached to their original nodes so that manipulating
named nodes transforms the meshes
- We block same-parent mesh merging if one of the nodes is named since
named transforms may change
Fixes #48.
> gltfpack: Implement support for keeping named nodes

- CMakeLists.txt
Adds the ability to build as a shared library using the global CMake option BUILD_SHARED_LIBS
> Support BUILD_SHARED_LIBS

- CMakeLists.txt
- meshoptimizerConfig.cmake.in
Adds an install target with config-/export-based `find_package` support. Usage example for the installed version:
```cmake
find_package(meshoptimizer REQUIRED CONFIG)
target_link_libraries(<some_target> PRIVATE meshoptimizer::meshoptimizer)
```
Note that the current version must be passed to `project` (also, `cmake_minimum_required` should be called *before* `project`).
> Add a CMake install target

- CMakeLists.txt
- demo/main.cpp
- src/meshoptimizer.h
- src/spatialorder.cpp
- tools/gltfpack.cpp
These functions are designed to sort vertices or triangles by the
spatial proximity. The goal is to improve spatial locality to make
other, subsequently ran algorithms, perform better.
Currently the implementation is using Morton order, which is a
reasonable proxy but in the future we will try to use a kD tree sort.
This PR also uses the new functions to sort point cloud meshes in
gltfpack.
This substantially increases the compression efficiency; for example,
kitchen.gltf before this change had almost incompressible data (24.5
bits color, 48.0 bits positions) due to the random order. After this
change, the color gets compressed to 16.5 bits and positions get
compressed to 20.1 bits.
> spatial: Introduce spatialSort and spatialSortTriangles

- tools/cgltf.h
- tools/gltfpack.cpp
We now preserve morph target names if present in the source glTF file;
meshes with the same set of targets but with different names aren't
merged to preserve name mapping.
This required extending cgltf to parse target names; patch will be submitted
to cgltf repository separately.
Fixes #61.
> gltfpack: Implement targetNames support

- .travis.yml
- CMakeLists.txt
- CMake project now specifies C++ as a project language, which saves ~10 seconds on configuring C compiler in CMake
- All make invocations use two cores for a ~5 second speed boost on macOS/Linux builds
> CI build performance improvements

- .github/workflows/ccpp.yml
- .github/workflows/main.yml
- Makefile
This adds integration with GitHub Actions in addition to Travis CI; everything except for Linux/clang build is supported here, including code coverage reports.
> Add GitHub Actions build

- README.md
- demo/GLTFLoader.js
- demo/index.html
- demo/main.cpp
- src/meshoptimizer.h
- src/simplifier.cpp
- tools/gltfpack.cpp
This change adds two new command-line arguments, -si R (to specify the simplification ratio) and -sa (to enable aggressive simplification). Each mesh in the output is simplified to the given ratio; when aggressive simplification is enabled, the target ratio is reached disregarding change in appearance.
Supporting this for point cloud meshes required a new algorithm, `meshopt_simplifyPoints`; this uses a variant of sloppy simplifier with the quadric error based on distances to points. This is an experimental addition and will probably need to be refined (in particular, attribute error is pretty important for point clouds).
In the future the aggressive mode can be refined a bit further by trying to simplify the mesh with the default simplifier on a subset of attributes in some cases (e.g. …
> gltfpack: Add simplification options

- .github/workflows/build.yml
- src/vertexcodec.cpp
This change merges the GitHub configurations for macOS and Linux into
one which adds support for coverage reports from macOS/clang.
> Merge Linux and macOS builds

- .travis.yml
This lets us test the NEON version of the vertex codec in CI. Before this change, we were building the vertex codec for armv7 and aarch64 on macOS, but didn't have a way to test it. Now we can run the tests as well, including code coverage.
> Add ARM64 config to Travis CI

- tools/cgltf.h
- tools/gltfpack.cpp
This change updates cgltf.h to the latest version that supports sparse accessors through cgltf_accessor_unpack_floats and refactors the code to use this.
Additionally, this surfaced an issue with morph target animations - we were mistakenly removing morph weight tracks that were constant with the first weight being equal to 0; for now we preserve all constant
morph weight tracks instead.
> gltfpack: Add support for sparse accessors

- .travis.yml
- demo/main.cpp
- js/meshopt_decoder.js
- src/vertexcodec.cpp
This change adds AVX512 and WASM SIMD support for vertex codec.
AVX512 version gives a minor speedup compared to SSSE3 version - it's ~10% faster to decode; however it also is ~2x smaller which is nice-to-have. Because the speedup isn't very significant we only activate this version if AVX512 instructions are declared to be supported - this happens in gcc/clang when -march=icelake-client is specified. Note that the implementation requires AVX512VL and AVX512VBMI2.
WASM SIMD version is around 3 times faster than the scalar version, which is about the same speedup that SIMD gives for native versions. This currently only works on the bleeding edge of the entire ecosystem - requires several fixes in LLVM/binaryen and Chrome Canary to support swizzle and some other instructions.
Note that WASM …
> Improve SIMD support in vertex codec

- tools/gltfpack.cpp
When -te flag is specified, this change embeds all textures into
buffers, including those referenced through URIs in the original file.
This leads to all textures being packed into the .glb or .bin file.
> gltfpack: Implement optional texture embedding

- tools/gltfpack.cpp
When -tb is specified, we run all textures from the input asset through
Basis, and place the results into .basis folder next to the scene asset.
Embedding textures is supported using image/basis MIME type although
this is not supported by any glTF renderers - the plan is to migrate this code
to use KTX2 once there's some support for it anywhere.
Also normal encoding quality is pretty bad - it requires splitting the image into
two channels, which again isn't supported by any existing renderers.
> gltfpack: Impement support for Basis texture conversion

- tools/gltfpack.cpp
When we can't use fixed point quantization (translation/rotation), we
fall back to floating-point quantization which leaves the least
significant mantissa byte as 0. This results in noticeable improvement
in compression ratio - on two examples, translation track got ~1.6x
smaller (64->40 bits in one case and 40->24 in another).
It remains to be seen how acceptable the quality reduction here is - I'm
worried about translations in particular as there are extreme cases
(e.g. an object moving from 0 to 1000) where this type of change makes
the destination of the movement noticeably off (precision around 1000
drops from 6.1e-5 to 1.6e-2).
> gltfpack: Quantize floating-point values for keyframe tracks

- demo/GLTFLoader.js
- tools/gltfpack.cpp
This change tweaks Basis support a bit - you can now customize the path to basisu via BASISU_PATH environment variable.
It also extends demo/GLTFLoader.js with direct support for image/basis MIME type and .basis extension. The extension customization is possible by using regexp-based loader handlers, but MIME type customization has to be hacked into the glTF loader, unfortunately. I don't expect this solution to persist forever but without this it's hard to test Basis content properly.
> gltfpack: Minor Basis tweaks and demo integration

- CMakeLists.txt
- Makefile
- src/vertexcodec.cpp
- tools/basistoktx.cpp
- tools/basisu_format.h
- tools/gltfpack.cpp
- tools/khr_df.h
- tools/ktx2_format.h
This change adds -tc command line flag that uses basisu command line tool to compress images using Basis Universal format, and then converts the result to KTX2 container format.
The resulting images are then referenced from the output gltf/glb file using KHR_texture_basisu and KHR_image_ktx2 extensions.
> gltfpack: Implement support for KTX2 with supercompression

- tools/cgltf.h
- tools/gltfpack.cpp
This change makes gltfpack more robust when processing files that aren't valid or clean. In particular:
- Error messages for various invalid files are now cleaner, with glTF 1.0 files highlighted specifically
- Meshes can now become empty during processing (e.g. all triangles are degenerate) and will be skipped; associated nodes are still emitted for now
- Dummy buffers can no longer be referenced from accessors - this caused NULL pointer dereference before
- Index data is now correctly validated before use
> gltfpack: Improve robustness when dealing with invalid files

- demo/tests.cpp
- src/vertexcodec.cpp
This change uses clang/gcc support for "target" attribute so that by default, we use SIMD decoder in basically all cases.
This eliminates our code coverage on scalar decoding path :-/ Not sure how to deal with this yet.
> vertexcodec: Automatically enable SIMD with fallback for clang/gcc

- tools/gltfpack.cpp
Instead of just omitting stream cleanup during stream writes, we now
remove redundant streams as early as possible during mesh processing.
This can reduce the data size by improving reindexing results in some cases
as well as improve the quantization quality due to a reduced UV range.
Also we now filter out redundant color streams and, if color streams aren't
redundant, correctly initialize vertex alpha if it's absent in the source.
> gltfpack: Improve stream filtering

- tools/cgltf.h
- tools/gltfpack.cpp
This change reworks the animation processing pipeline to resemble that of meshes - animations are separately parsed, processed (optimized) and written. This allows us to more easily analyze and optimize animations in different ways.
This change also switches the error function for rotation and scale; rotations now use relative rotation angle (in radians), and scale uses relative scale delta from 1. This increases the size of some files where we previously culled rotation animations too aggressively.
Also morph target weight animations now also support dummy track optimization, so occasionally the files are smaller.
> gltfpack: Rework animation processing pipeline

- CMakeLists.txt
VERSION_GREATER_EQUAL is not available on older CMake versions.
> Fix build on Android (CMake < 3.7).

- tools/gltfpack.cpp
This substantially improves the texture distortion for models that have
different textures that are used with different tiling factors.
This doesn't go as far as it could in terms of improving the quality -
we could split vertices in highly tiled meshes and/or rearrange UV
islands to get a better result, and we could start duplicating materials
to improve this. However, it's a good first step.
Note that this change intentionally keeps a single transform per
material for now to make it easier for renderers to support gltfpack
compression - some renderers support more than one texture matrix per
mesh but not all might.
~Additionally this change switches to using normalized coordinates for texture
data - which shouldn't make a big difference one way or the other.~
Fixes #93.
> gltfpack: Use a separate texture coordinate transform per material

- .github/workflows/build.yml
We now run gltfpack on models from glTF-Sample-Models to prevent future
regressions.
> Add gltfpack to CI

- .github/workflows/build.yml
We now convert all .gltf models using gltfpack and run them through
gltf-validator to make sure the output is valid.
> Add gltf-validator to gltfpack CI

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/json.cpp
- gltf/material.cpp
- gltf/write.cpp
When a new flag, -ke, is set, we are starting to preserve .extras data in several objects.
This PR does it for materials only for now.
Closes #108.
> gltfpack: Implement "keep extras" flag

- extern/basisu_format.h
- extern/khr_df.h
- gltf/basistoktx.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
- gltf/write.cpp
This change adds a flag, -tu, that enables UASTC support both when encoding raw .basis files, and when encoding .ktx2 files.
The .ktx2 implementation may not be fully correct since the KTX DataFormat specification isn't fully complete here.
The .basis implementation has been tested using https://github.com/mrdoob/three.js/pull/18943.
Note that this change does *not* have RDO support - RDO encoding in basisu is *really* slow, and I'd need to figure out how to best map quality to the UASTC input parameters.
Additionally this change fixes support for basisu 1.12 and - miraculously - allows us to compress basis textures from Node as long as basis executable is available...
> gltfpack: Implement UASTC support

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
- gltf/parsegltf.cpp
- gltf/stream.cpp
- gltf/write.cpp
We now support points, triangles and lines in the backend; frontend
converts all other primitive types during parsing.
Index buffers that don't contain triangle lists are encoded using new sequence codec.
The only combination we don't support now is indexed points.
> gltfpack: Implement support for all primitive modes

- src/vertexfilter.cpp
- tools/codecbench.cpp
This results in dramatic performance improvements for native builds:
master:
filter: oct8 74.12 ms (0.40 GB/sec), oct12 74.17 ms (0.80 GB/sec), quat12 75.14 ms (0.79 GB/sec), exp 4.56 ms (13.07 GB/sec)
filter-sse:
filter: oct8 13.32 ms (2.24 GB/sec), oct12 13.80 ms (4.32 GB/sec), quat12 19.66 ms (3.03 GB/sec), exp 4.57 ms (13.06 GB/sec)
The change also makes quat scalar filter slightly faster and simpler by not using a lookup table.
> vertexfilter: Optimize vertex filters using SSE2

- gltf/write.cpp
Encoding basisu/ktx2 textures fails if the mime_type is not setup.
basisu command fails if the input file has the extension `.raw` instead of `.png`.
Happened when converting glTF-JSON (with separate texture file) to glTF-JSON (with -tc option).
Tried to upload a sample file, but github throws errors :/
> gltfpack: Fixed missing mime_type

- Makefile
This will affect `codecbench`'s code size (probably not a high area of concern) but will make the generated Wasm much easier to analyze. Alternately, we could make the `WASM_FLAGS` variable more generic (which would involve some refactoring) and include the `-g` there.
> Build Wasm versions of codecbench with debug symbols

- .github/workflows/build.yml
- src/vertexfilter.cpp
Scalar performance:
oct8 231.26 ms (0.13 GB/sec), oct12 231.22 ms (0.26 GB/sec), quat12 179.14 ms (0.33 GB/sec), exp 19.04 ms (3.13 GB/sec)
NEON performance:
oct8 62.71 ms (0.48 GB/sec), oct12 69.98 ms (0.85 GB/sec), quat12 73.33 ms (0.81 GB/sec), exp 19.06 ms (3.13 GB/sec)
Note: the NEON code only compiles on AArch64 at the moment, which will need to be fixed before merging this.
>  vertexfilter: Implement NEON versions for all filters

- Makefile
- src/vertexcodec.cpp
- src/vertexfilter.cpp
This allows building codecbench with no SIMD code but still with optimizations enabled. @zeux, there is likely a clearer way to do this so feel free to ask for changes or commit to this branch! The rationale for this is to build an optimized, scalar version of codecbench.
> Add 'config=scalar' build flag

- src/vertexcodec.cpp
- src/vertexfilter.cpp
This change moves includes out of the SIMD auto-detection to streamline
the flow a bit, and adds explanation for each conditional section.
Also enables NEON vertexfilter code for MSVC which compiles without
issues.
> Refactor SIMD autodetection logic

- CMakeLists.txt
Just a minor buildsystem thing. 
`BUILD_SHARED_LIBS` got renamed to `MESHOPT_BUILD_SHARED_LIBS` by @corporateshark in #91, but the unprefixed variant is what still needs to be set for `add_library()` to work as desired. Without this, enabling `MESHOPT_BUILD_SHARED_LIBS` still produced an `*.a` file and additionally made CMake complain about visibility presets being set for static libs.
By the way, I packaged the latest release for ArchLinux and will be maintaining it for the foreseeable future (https://aur.archlinux.org/packages/meshoptimizer/), would it make sense to mention it in the README?
Thank you!
> CMake: make shared libs work again

- .editorconfig
- src/vertexfilter.cpp
*(I have to admit my monster [build matrix](https://magnum.graphics/build-status/) contains a bunch of outdated systems.)*
On Apple platforms, `__clang_major__` follows a different versioning scheme and version 8 is actually vanilla Clang 3.9, which made the build fail due to `__builtin_rotateleft64` not being defined. Extended the condition to check for version 11 instead if the compiler is Apple Clang. [Version mapping table on Wikipedia](https://en.wikipedia.org/wiki/Xcode#Toolchain_versions) for reference.
Also added an [.editorconfig](https://editorconfig.org) so editors implicitly know to indent with tabs plus a bunch of other good defaults.
> Fix build on old Apple Clang versions

- .github/workflows/build.yml
- extern/cgltf.h
This makes sure gltfpack and the algorithms it uses are sanitizer-clean
and that gltfpack doesn't leak memory.
This required fixing a few memory leaks in cgltf.
> Use config=sanitize for gltfpack testing

- extern/cgltf.h
- gltf/parsegltf.cpp
- gltf/write.cpp
We now decode URIs before trying to read buffer or image files, which fixes conversion for files with whitespaces in image paths.
Also improve needsDummyBuffers to make sure that buffers referenced by images have data loaded by cgltf_load_buffers.
Fixes #138.
> gltfpack: Implement URI decoding for image/buffer paths 

- demo/GLTFLoader.js
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
- gltf/node.cpp
- gltf/parsegltf.cpp
- gltf/write.cpp
This change reworks the gltfpack mesh processing pipeline to be instancing-friendly: instead of duplicating all mesh instances during parsing, we keep the instance data if possible throughout the pipeline.
By default gltfpack no longer merges multiple instances of the same mesh together; this behavior can be changed using `-mm` command-line switch (which usually generates fewer draw calls for scenes with duplicate geometry, at the expense of using more memory).
This change also implements experimental support for EXT_mesh_gpu_instancing, which can be activated using `-mi` switch. The instance data is saved in the same format as animation keyframes, which doesn't fully match the current spec draft.
> gltfpack: Implement mesh instancing

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/material.cpp
- gltf/mesh.cpp
- gltf/node.cpp
- gltf/write.cpp
This change reworks -kn and -km to explicitly assume naming - the behavior of kn is unchanged, but km now only keeps named materials, and also disables material merging for named materials to ensure that changing these materials at runtime is possible.
Additionally -ke now writes extras for nodes as well.
Follow-up to #143.
Fixes #144.
> gltfpack: Improve behavior of -kX flags

- Makefile
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/parsegltf.cpp
- gltf/parseobj.cpp
- gltf/write.cpp
This change makes gltfpack more memory efficient when processing large scenes through a combination of being more efficient with memory allocations and freeing excess memory early:
- Mesh and animation parsing now doesn't reallocate vectors
- Buffers that aren't referenced by skin or image data are freed before scene processing
- Fallback buffer contents is not generated anymore unless requested
- GLTF JSON blob is now freed very early during parsing when processing .gltf inputs
As a result, a JSON-heavy scene goes from 121 MB to 75 MB of RSS for processing (-38%), and a mesh-heavy scene goes from 1390 MB to 810 MB (-42%); so it looks like we now need ~40% less memory on average.
Additionally, this change switches gltfpack.js to 4GB builds, so that with recent v8 it can use the full …
> gltfpack: Substantiall reduce memory footprint

- .github/workflows/build.yml
- gltf/parsegltf.cpp
We would free the buffer that's backing the binary data since we don't
need it anymore but the buffer object would still point to the
deallocated memory, causing a crash when cgltf_free frees it later.
This is a regression from #147; it was missed because the CI didn't
test gltfpack on .glb files - well, now it does.
> gltfpack: Fix processing for .glb files with no images

- demo/tests.cpp
- gltf/mesh.cpp
- src/meshoptimizer.h
- src/simplifier.cpp
Instead of only looking at the outgoing open edges during
classification, we now look at both incoming and outgoing edges.
This cleans up the classification results in some rare cases and opens
up doors for more robust analysis of borders and more opportunities for
collapsing, e.g. seam -> locked, in the future.
It also allows us to use the open edge data for edge quadrics - essentially we
now have a bidirectional edge loop structure instead of the unidirectional one.
This is implemented using just binary hasEdge operator which means we almost
don't need EdgeAdjacency anymore (but keeping it for now in case it proves useful).
Fixes #122 
Fixes #88 (or, well, it makes it better; there are still some problems in Lumberyard but it's a huge scene and it's hard to analyze - will need a better …
> simplify: Implement more robust open edge analysis

- gltf/README.md
- gltf/fileio.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
- gltf/write.cpp
There were several things that made it so that Basis encoding for gltfpack.js only worked in Linux/macOS hosts and only if basisu was available via PATH.
This change fixes the issues by using a custom system() implementation to suppress stdout/stderr, a different way to generate temp paths under Emscripten, and a custom getenv() replacement to support BASISU_PATH.
Fixes #137.
> gltfpack: Implement Basis support in node.js builds

- demo/THREE.EXT_meshopt_compression.js
- demo/index.html
- gltf/README.md
Instead of using demo/GLTFLoader.js we now use the plugin infrastructure
added in r118 to load files with EXT_meshopt_compression.
Since three.js is going to deprecate non-module-based examples, the
THREE extension is using `export` as well to conform to the overall style.
Unlike demo/GLTFLoader.js, this method doesn't support mesh instancing
or embedded Basis textures, but this hopefully will be added to
three.js in the future, and for now demo/GLTFLoader.js is still here.
> demo: Update to three.js r118 and start using plugins

- demo/THREE.EXT_meshopt_compression.js
- demo/babylon.EXT_meshopt_compression.js
This allows overriding the name post-construction externally to work
with legacy files, for example
loader.register(function (parser) {
var res = new EXT_meshopt_compression(parser, MeshoptDecoder);
res.name = "MESHOPT_compression";
return res;
});
> demo: Use this.name for looking up glTF extensions

- extern/khr_df.h
- gltf/basistoktx.cpp
Crucially, globalFlags was removed from BasisU super-compression global data; this renders all existing files incompatible but such is life.
> gltfpack: Update KTX2 format to track latest specification

- README.md
I wanted to update to the latest version of `gltfpack` but it took me a minute to remember that `gltfpack` is in the `gltf` folder and to figure out the correct options to compile it with CMake. 
Then I read through recent issues and saw you posted a link to the the Actions page which contains binaries in the build artifacts
Probably a good number of people come to this repo to install gltfpack itself, so I figured it'd be helpful to mention on the main readme
> Add gltfpack installation instructions to main readme

- README.md
Following ArchLinux, meshoptimizer is now also available in Vcpkg (https://github.com/microsoft/vcpkg/pull/12211).
> Mention the Vcpkg package in README

- demo/GLTFLoader.js
- extern/cgltf.h
- gltf/gltfpack.cpp
- gltf/material.cpp
- gltf/write.cpp
This change simply propagates KHR_materials_transmission parameters
through, supporting material merging as well.
It also fixes a problem with texture set filtering, where we ignored
texture sets that might have only been used in clearcoat layer.
Also contains an unrelated fix to frustum culling in GLTFLoader.js, might as well submit it with this.
> gltfpack: Implement support for KHR_materials_transmission

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
- gltf/write.cpp
This change implements support for using toktx when compressing images to KTX2 via `-tc`.
This allows us to use zstd compression for UASTC images, and also sets us up to remove direct Basis support at some point in the future.
When toktx is not available, we fall back to basisu (if available) as before, so this shouldn't break any existing usage patterns.
This also implements a new option, `-ts`, that can rescale the textures by a given amount; toktx supports this via --scale.
Fixes #134.
> gltfpack: Implement support for toktx

- gltf/gltfpack.cpp
- gltf/image.cpp
This change changes the texture quality control to use fewer levels,
1-10, with a remap into Basis encoding settings.
The default quality is 8; 9 & 10 are trying to preserve quality more
aggressively, lower levels lose more quality and 1 & 2 are trying to
minimize the size and the encode time as well.
Notably, for UASTC encoding this change enables RDO for all modes; it
does it with a very small RDO dictionary (1024 bytes) because anything
larger than 2048 isn't very practical for encode times.
> gltfpack: Implement new texture quality scale 1-10

- extern/cgltf.h
- gltf/gltfpack.cpp
- gltf/image.cpp
- gltf/material.cpp
- gltf/write.cpp
This change also fixes clearcoat normal texture handling for Basis encoding and introduces support for scale/strength for normal and occlusion textures that was omitted before.
> gltfpack: Add support for KHR_materials_{ior,specular}

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
- gltf/node.cpp
- gltf/parsegltf.cpp
- gltf/parseobj.cpp
- gltf/wasistubs.cpp
- gltf/write.cpp
Before this change gltfack wasn't scene aware, and would process all
nodes regardless of which scene they come from.
With this change, we now output the same number of scenes that the input
file contained. When merging meshes and converting nodes to mesh instances,
the process is limited to cases where the mesh is not used in multiple
scenes.
Fixes #184
> gltfpack: Preserve scenes during processing

- .github/workflows/build.yml
- .gitignore
- Makefile
- gltf/README.md
- gltf/cli.js
- gltf/gltfpack.cpp
- gltf/image.cpp
- gltf/library.js
- gltf/package.json
- gltf/wasistubs.cpp
- gltf/wasistubs.txt
This PR reworks gltfpack Wasm module as a reactor that provides a function to run packing process.
It can be ran repeatedly with different inputs.
Instead of using the global argc/argv mechanism we simply pass the relevant data to the pack function; this allows to omit the WASI argc/argv implementation.
Instead of using getenv mechanism we replace the command on the JS side for the execute() function.
The WASI layer is implemented in a node.js-agnostic way, with file I/O using typed buffers (Uint8Array); cli.js uses node.js Buffer objects to implement these but an arbitrary implementation should be possible.
Here's a primitive example of running this in the web browser (without file I/O implemented):
```
gltfpack.init(fetch('./library.wasm').then(resp => resp.arrayBuffer())); …
```
> gltfpack: Provide a CLI and library version of gltfpack

- gltf/animation.cpp
- gltf/gltfpack.h
- gltf/write.cpp
When an animation consists exclusively of constant tracks, we would
previously export only a single keyframe for all tracks. This loses time
information that may be important for playback in case the pose is
sequenced for a given duration by the mixer.
To minimize the size impact, we expand exactly one track and only for
animations that don't have actual timed tracks; for that to work we need
to output a special input track with two time values, start and start +
(frames - 1) / freq, which should match the end time that we would emit
if any tracks had data.
Fixes #185.
> gltfpack: Preserve the time range for pose-only animations

- Makefile
- tools/codecfuzz.cpp
All codecs must be resistant to malicious inputs; while the decoders
aren't guaranteed to provide a valid result, they must be able to decode
the input without reading past the input bounds or writing past the
output bounds.
This change adds a fuzzing driver that attempts to prove this for both
SIMD and scalar implementations of the decoders.
> tools: Add fuzz driver for all codecs

- Makefile
This PR adds a rule in the Makefile to build the codecfuzzer in the OSS-fuzz environment.
> Add Make rule for OSS-fuzz

- demo/main.cpp
- demo/tests.cpp
- src/simplifier.cpp
Right now simplifier does not restrict edge collapses beyond
topology/quadric errors, which in some cases results in triangles
getting flipped.
This is a well known problem and a well known solution is to check
whether the triangles are flipped explicitly during collapse.
Unfortunately, the simplifier currently doesn't maintain enough data to
be able to perform this analysis; this change adds code to maintain a
second adjacency structure (that identifies triangles during collapse)
and uses it to validate collapses right before they happen.
~The current implementation seems to resolve existing issues with the
flipping but results in substantially worse simplification performance
(4-5x slowdown, most of the work seems to be in hasTriangleFlips). This
will *not* be merged in this state; I'm …
> simplify: Restrict edge collapses to avoid triangle flipping

- Makefile
The rule is not being used as it is now. It may be brought back at a later time, but it is being removed now to avoid having unused code.
> Removed ossfuzz make rule

- Makefile
- demo/main.cpp
- demo/tests.cpp
- src/meshoptimizer.h
- src/simplifier.cpp
This change adds an extra optional argument, `result_error`, to `meshopt_simplify` that can be used to output the error after the simplification, which - just like target_error - is a measure of the relative (0..1) deviation of the produced result from the source mesh. The argument is optional in C++ but required when C interface is used - NULL can be passed if this information isn't required.
When absolute errors are required instead, newly added `meshopt_simplifyScale` can be used to scale the input or the output error back into world space.
Fixes #59.
> simplify: Return error after simplification

- demo/main.cpp
- demo/tests.cpp
- gltf/mesh.cpp
- src/meshoptimizer.h
- src/simplifier.cpp
This change makes simplifySloppy interface match that of simplify, so
that an error limit can be specified up front, and the resulting error
is returned when requested.
As a consequence, simplifySloppy can no longer guarantee that the output
will be at or under the requested triangle count; this unifies the
interface between simplify & simplifySloppy further and gives us some
opportunity to compute triangle count in a more approximate way in the
future.
As a result we may need to compute the triangle count for the min. grid
size before simplification starts; this sometimes increases the number
of passes we need to do by 1, but in aggregate actually *decreases* the
number of passes as the interpolation search gets more data and can be
more precise.
Fixes #112.
> simplify: Add input & output error to simplifySloppy

- demo/main.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
- src/clusterizer.cpp
- src/meshoptimizer.h
In order to build meshlets that can be used in mesh shader based renderers and in other cases where cluster culling is valuable, we used to have a naive linear algorithm that converted a vertex cache optimized index buffer to meshlet sequence.
This algorithm mostly worked fine when the goal was to produce meshlets that don't need to be culled, but had suboptimal results when occlusion or cone culling was needed.
This change renames the old algorithm to buildMeshletsScan and introduces a new algorithm that generates high quality meshlet data regardless of the original triangle order, trying to balance meshlet packing efficiency (# of vertices/triangles), size (bounding radius) and triangle orientation.
Optimizing for radius and orientation presents conflicting goals; to maximize cone …
> Rework meshlet construction

- .github/workflows/build.yml
- extern/fast_obj.h
- gltf/gltfpack.cpp
- gltf/library.js
- gltf/package.json
When running gltfpack via a node.js build, absolute paths don't work
correctly, as /foo/bar is converted to foo/bar by wasi-libc.
This has to do with the path handling inside wasi-libc, where it looks
at the mounts; given an empty mount path it seems to treat /foo/bar as
mount-relative *and* returns the leading slash which would make sense
for non-empty mount paths.
To work around this, we use the recently introduced chdir support in
wasi-libc. A fake path /gltfpack-cwd is registered as current, and
accesses to that path map to "", which seems to preserve relative paths.
To that end, library.js now implements a slightly more generic version
of mounts, and a stub for path_filestat_get which is needed to get chdir
to work.
Also includes fixes to fast_obj for slash handling so that Windows …
> gltfpack: Fix handling of absolute paths on node.js

- README.md
- demo/main.cpp
- gltf/mesh.cpp
- src/clusterizer.cpp
- src/meshoptimizer.h
The existing interface for meshlet construction used fixed size arrays
as part of meshopt_Meshlet structure. This was hard to extend - on AMD
hardware larger meshlet sizes may be appropriate, and increasing the
size of the arrays in the structure results in subtantial increase in
memory consumption for older limits.
In addition, meshopt_Meshlet should be regarded as an intermediate
structure as it's not appropriate for direct consumption on GPU, but
that's in contrast with other algorithms in meshopt that usually produce
data fit for GPU.
This change thus reworks the meshlet algorithms to work with packed
vertex index / triangle data. This allows us to be flexible wrt the max
meshlet size.
When writing out vertex indices, we pack them tightly; for triangle
indices we align each meshlet to …
> clusterizer: Rework meshlet interface to use SoA results

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/material.cpp
When -noq is used we still may need to preserve KHR_texture_transform in
extensionsUsed if it was used in the source scene in one of the
materials.
Fixes #227.
> gltfpack: Properly handle KHR_texture_transform extension

- README.md
This PR adds a link to Debian und Ubuntu, which also ship the meshoptimizer library.
> Add reference to Debian and Ubuntu packages

- demo/main.cpp
- demo/tests.cpp
- src/indexgenerator.cpp
- src/meshoptimizer.h
To render a mesh with normal/UV seams using hardware tessellation, the
PN-triangles method is not sufficient as it produces cracks on normal
discontinuities (position displacement based on normal is not consistent
along both sides of the seam), and displacement mapping uses slightly
different texture samples which results in cracks along UV seams.
In 2010, NVidia proposed a PN-AEN tessellation scheme that fixes the
problem around normal discontinuities by using opposite edge normals and
averaging the resulting control point data. In 2011, NVidia proposed a
further tweak on top of this technique that allows to select the
"dominant" edge by choosing the min. edge index out of the
current/adjacent edges, and using the UV data from that edge on the
patch edges to sample the displacement data. …
> indexgenerator: Implement support for PN-AEN tessellation buffers

- demo/main.cpp
- demo/tests.cpp
- src/indexgenerator.cpp
- src/meshoptimizer.h
Several algorithms that use geometry shaders to render data require
adjacency information; triangle-with-adjacency topology in various APIs
provides a way to supply 3 extra vertices per each triangle that
represent vertices opposite to each triangle's edge.
This data can then be used to compute silhouettes and perform other
types of local geometric processing.
This change implements the data preprocessing step that is similar to
the previous tessellation IB - but instead of storing vertices that
adjoin the triangle from the opposite side, we need to store
complementary / opposite vertices of adjacent triangles, which requires
a separate temporary table.
> indexgenerator: Implement support for triangle adjacency index buffers

- extern/cgltf.h
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
- gltf/material.cpp
- gltf/mesh.cpp
- gltf/write.cpp
This change adjusts the implementation of KHR_materials_specular; the
last update to the specification split the single texture (RGB+A) into
two separate texture slots (RGB + A). This requires associated changes
to handle the case when these are separate.
It also takes an opportunity to rework material analysis to consolidate various
material-related queries. This fixes a small corner case where tangents could be
removed from a mesh that's using clearcoat normal map, and paves the way
towards material variants where mesh processing would need to use combined
material info from all variants.
> gltfpack: Update KHR_materials_specular to match new draft

- extern/cgltf.h
- gltf/gltfpack.cpp
- gltf/material.cpp
- gltf/write.cpp
This extension is in draft but the specification is reasonably complete.
This change adds support for the extension as well as fixing a bug with
KHR_materials_specular writing.
> gltfpack: Add support for KHR_materials_volume

- extern/cgltf.h
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/material.cpp
- gltf/mesh.cpp
- gltf/parsegltf.cpp
- gltf/stream.cpp
We now process all variant materials similarly to other materials and emit material mapping and variant data in the output.
Mesh merging is restricted to cases when the variant set is identical.
Fixes #233.
> gltfpack: Implement support for KHR_materials_variants

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
While filtering redundant streams during mesh optimization almost always
works well, there are rare cases where the input meshes have
inconsistent redundant streams (that block merging), and even though
these streams are removed that happens too late after the merging has
already been done.
This change splits off stream filtering from general mesh processing so
that we can run it early. This also slightly simplifies the flow since
we only need combined material information for filtering anyhow.
Reported in https://github.com/zeux/meshoptimizer/discussions/262.
> gltfpack: Restructure mesh processing to filter streams first

- gltf/cli.js
- gltf/gltfpack.cpp
- gltf/image.cpp
We had multiple bugs around handling texture compression via an external executable.
One, on node.js the environment variable *had* to be set (just adding executable to PATH didn't work because of a bug in the JavaScript wrapper); when the variable contained a path with spaces on Windows, the executable couldn't be found because the spaces weren't quoted in the shell execution.
Two, on Windows when the environment variable was set to a path with spaces, the executable couldn't be found either due to quotation issues.
We now correctly quote the paths on Windows and handle the executable spawning with a bit more care in node.js.
Originally raised in https://github.com/zeux/meshoptimizer/discussions/247.
> gltfpack: Fix various issues with texture compression

- CMakeLists.txt
CMP0077 requires >= 3.13
CMP0091 + CMP0092 requires >= 3.15
we hit this bug here: https://github.com/spring/spring/pull/559/files#diff-48b508d8a5702095973f36f384be2a8b74834092bb7ed47c536f1af80015b20bR4
> fix checks in CMakeLists.txt

- extern/cgltf.h
fix: when loading a gltf with "KHR_lights_punctual" extension with lights with no intensity (default 1), the gltf was saved with intensity 0 (instead of 1 or actually nothing because it's the default)
> KHR_lights_punctual: intensity light default to 1

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/write.cpp
Currently, meshoptimizer completely ignores information about textures' samplers stored in the glTF file. The attempt of this pull request is to fix that.
> Pass textures' samplers to optimized files

- gltf/basistoktx.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
- gltf/write.cpp
When -tfy is specified, textures are flipped alongside Y axis during
texture compression by passing an extra argument to toktx or basisu.
This is helpful for some applications that expect a different coordinate
system.
Fixes #241
> gltfpack: Implement support for texture flipping 

- gltf/animation.cpp
When analyzing track errors, currently gltfpack doesn't take the
hierarchy into account. This is known to be problematic in some cases -
ideally, all errors need to be analyzed at leaf level which would take
into account the entire hierarchy to make sure that each constant
folding doesn't affect the final result too much.
For now, this fixes one egregious and potentially common case where when
a scene root has a large scale (which is common for cases where scenes
go through a unit conversion), the visual error gets magnified by this
scale, which can result in a visible degradation of animation quality.
Fixes #278.
> gltfpack: Fix translation track optimization to take scale into account

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
- gltf/material.cpp
- gltf/write.cpp
You can now specify the texture class with `-tu` and `-tq` options to customize compression parameters for different types of textures - for example, this makes it possible to use UASTC for normal maps but keep ETC1S for other textures.
The set of classes is specified after the relevant option as a comma-separated list and can consist of `color`, `normal` and `attrib`. The parameters are parsed left to right and override each other in that order, so a class-less option should be specified before options with classes.
Fixes #273.
> gltfpack: Implement per-class texture compression options and statistics

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
- gltf/material.cpp
- gltf/write.cpp
- src/clusterizer.cpp
- src/simplifier.cpp
- src/vertexfilter.cpp
This relies on extracting image metadata from all images, which means we
now always read image data at least once when processing scenes; but the
benefit is that we can now remove incorrect BLEND modes from materials
which seems worth it.
> gltfpack: Remove BLEND mode from materials that don't need it

- CMakeLists.txt
- Makefile
This is going to make Basis integration easier; there's no real reason
to keep using C++98 for gltfpack. Note that meshoptimizer continues to
use C++98 and that is unlikely to change.
> gltfpack: Switch to C++11

- demo/tests.cpp
- src/meshoptimizer.h
- src/vertexfilter.cpp
These allow encoding data from a floating-point source into the format that meshopt_decodeFilter* will recognize.
gltfpack doesn't use these yet since it also needs basic quantization methods that might be exposed as meshopt_encode* in a separate change.
> Add meshopt_encodeFilter* function family

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/write.cpp
The volume thickness factor is specified in coordinate space of the mesh
-- changing this coordinate space results in a different thickness. As
such, we can't transform the mesh so when instancing is disabled we need
to keep the mesh attached to the original node, and we need to adjust
the thickness factor in all volume materials by the quantization scale.
Fixes #328.
> gltfpack: Fix quantization interaction with KHR_materials_volume

- gltf/animation.cpp
This change adjusts the translation tolerance to make it 10x stricter which fixes some edge cases when translation tracks are collapsed erroneously (without affecting the efficiency on regular content), and makes rotation tolerance slightly more lax - we previously used 0.57 degrees and now we use 0.1 degrees to use more round numbers.
This change also reworks the code that estimates deviation to make it easier to debug for future cases like this.
At some point it may make sense to start preserving tracks as is when `-ac` is specified instead of just disabling keyframe collapse; however, most of the constant tracks are also dummy, and so we might need a new command line key to avoid having users who need `-ac` for other reasons to pay the penalty.
Fixes #332.
> gltfpack: Adjust animation tolerances

- Makefile
- src/vertexcodec.cpp
- src/vertexfilter.cpp
make codecbench.wasm and make codecbench-simd.wasm now use WASI SDK
instead of Emscripten; it's necessary to use recent clang and set
WASI_SDK to point to a wasi-sysroot.
make codecbench.js and make codecbench-simd.js will continue using Emscripten,
and now use single-file builds to avoid generating .wasm artifacts.
Closes #339.
> Add WASI SDK build for codecbench

- gltf/gltfpack.cpp
- gltf/image.cpp
- gltf/material.cpp
- gltf/write.cpp
Do not write out several options if at the default values.
Texture view transforms were a bit difficult as several places check for the extension being used - I broke "const" in updating the values during the material analyse phase as I could not easily see another obvious place to change this.
Sorry this also includes the PNG change, I could not figure out how to cherry pick in github easily.
> Optimize output types

- gltf/gltfpack.cpp
This makes sure that on Linux, where the locale may be set to non-C when
the program starts, we still use dot as a decimal separator.
Fixes #366
> gltfpack: Set locale to C

- gltf/write.cpp
This fixes issues for some animations where because we didn't preserve
STEP, during playback different keyframes that were never supposed to be
interpolated would be interpolated resulting in unexpected values.
Note that we only need to do this for STEP because LINEAR is the
default, and we resample CUBICSPLINE to LINEAR.
Fixes #341.
> gltfpack: Preserve interpolation type for STEP tracks

- gltf/basisenc.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
This option allows overriding the number of jobs used to compress
textures. For now we simply forward the option to the respective command
line tool.
When Basis is compiled in, this change switches to a shared job pool
which avoids the overhead of reinitializing it for every compression
job.
> gltfpack: Add -tj command line option

- gltf/basisenc.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
Instead of encoding one image at a time and letting Basis do internal
threading we now encode images in parallel using two job pools, one for
actual encoding and another one for farming out Basis encoding jobs.
As a result the compression is much faster, eg jrat.gltf encodes in ~20
seconds before this change and in ~7.5 seconds after it on Ryzen 5900X.
Note that we use two pools but their use isn't very well balanced;
depending on the mode we aren't running as fast as we possibly could, eg
changing both pools to max out logical processor count gets us to 5.5
seconds on the same input. However this would mean that we'd overload
the system so for now we're going to stay conservative.
> gltfpack: Compress textures in parallel

- extern/cgltf.h
- gltf/gltfpack.cpp
- gltf/material.cpp
- gltf/write.cpp
This also updates cgltf.h to latest to get support for this extension.
> gltfpack: Add support for KHR_materials_emissive_strength

- gltf/basisenc.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
This change builds on top of https://github.com/zeux/basis_universal/commit/3c5d651357e75f854f60aa5a65acda4e79e45148
and merges two pools which results in much better scalability, before
this the CPU utilization of gltfpack on large scenes was ~80% during
texture compression and now it's ~100%.
> gltfpack: Switch to token-based pool from basis_universal fork

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
When -tl is set, we rescale textures so that the maximum dimension is within the
specified limit; the scaling preserves aspect ratio, eg 1000x100 texture gets
rescaled to 128x12 with -tl 128.
> gltfpack: Implement a new setting to limit texture dimensions

- gltf/mesh.cpp
This slightly regresses the compression ratio but the delta is not very significant -
it seems to be <~0.1% on most meshes and goes up to ~0.3% on some.
We can probably recoup some of the losses by sorting the skin joints in the future
by making the neighboring joints more spatially proximal wrt rigging.
With this change renderers that discard lower weights and renormalize the rest will
not have to sort the weights for glTF files packed by gltfpack in the future, even
though there's no way to indicate that in the file for now.
> gltfpack: Sort bone influences by weight, not by index

- src/allocator.cpp
- src/meshoptimizer.h
> Added `MESHOPTIMIZER_ALLOC_CALLCONV` (fixes #403)

- extern/cgltf.h
- gltf/gltfpack.cpp
- gltf/material.cpp
- gltf/write.cpp
The extension is effectively finalized and unlikely to change at this point.
Spec: https://github.com/KhronosGroup/glTF/pull/2027
> gltfpack: Implement support for KHR_materials_iridescence

- gltf/README.md
- gltf/basisenc.cpp
- gltf/basislib.cpp
- gltf/cli.js
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
- gltf/library.js
- gltf/wasistubs.cpp
- gltf/write.cpp
The rationale for this is described in #418. At this point builtin support for BasisU compression is superior in terms of ease of distribution and performance, and the maintenance burden of executable-assisted compression is too high.
The most notable change here is that gltfpack loses support for texture compression from node.js builds. When texture compression is required, using a native build of gltfpack fixes this and provides greater performance over currently available options anyway.
Fixes #418.
> gltfpack: Stop supporting texture compression via external executables

- CMakeLists.txt
This may be needed when creating setup packages.
> CMake: Updated install script, added COMPONENT.

- demo/main.cpp
- demo/tests.cpp
- src/meshoptimizer.h
- src/simplifier.cpp
This change adds option bitmask to `meshopt_simplify` and adds an option
that allows to lock the topological border, which can be valuable to
ensure that multiple parts of the same, larger, mesh can be simplified
in isolation and then stitched together.
This is the last change to `meshopt_simplify` signature; new options will
either be added as an option bit, which preserves binary interface, or
will be part of new functions such as `meshopt_simplifyAttributes` or
`meshopt_simplifyExtended` if we need to add more than just attributes to
the API.
Fixes #311.
> simplify: Add meshopt_SimplifyLockBorder option

- .github/workflows/build.yml
- .github/workflows/release.yml
Unfortunately npm doesn't seem to allow using external files as part of
the package, so we need to copy the file into the folders before
building, which makes it so that npm picks it up.
This change also moves the build actions that actually produce NPM
artifacts to release workflow to more cleanly isolate that from
build/test.
Fixes #434.
> Add LICENSE.md to npm packages

- gltf/basisenc.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/write.cpp
Now -tc option supports the same texture kind/mask specification as
options -tu and -tq; this allows to compress color/attribute textures
but leave normal maps uncompressed.
When only `-tu` option with a mask is specified, we used to compress
the textures not covered by the mask with ETC1S, but we now simply
don't compress them at all - hopefully this doesn't break anyone's
expectations! It's simple to go back to the old behavior by adding `-tc`
before `-tu mask`.
Fixes #438.
> gltfpack: Support partial texture compression with -tc

- gltf/parseobj.cpp
- src/indexgenerator.cpp
With this change we now deduplicate face vertices before creating the
vertex data, and don't create streams that we know don't exist.
This results in memory savings for loading large .obj files, although
this also regresses some:
Before:
./gltfpack -i /home/zeux/Downloads/rungholt.obj -o rh.glb 3.84 sec 924576 KB
./gltfpack -i /home/zeux/Downloads/hairball.obj -o hb.glb 1.36 sec 600440 KB
./gltfpack -i /home/zeux/Downloads/splash.obj -o sp.glb 15.12 sec 4249600 KB
After:
./gltfpack -i /home/zeux/Downloads/rungholt.obj -o rh.glb 3.91 sec 1100132 KB
./gltfpack -i /home/zeux/Downloads/hairball.obj -o hb.glb 1.26 sec 275084 KB
./gltfpack -i /home/zeux/Downloads/splash.obj -o sp.glb 12.06 sec 2766064 KB
It's not clear where the regression on rungholt comes from, although the
peak memory …
> gltfpack: Optimize .obj parsing for memory consumption

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/stream.cpp
- gltf/write.cpp
This change adds -vpn flag that enables the use of normalized position
accessors instead of integer (unnormalized) ones, and switches texture
coordinates to normalized attributes unconditionally.
Currently gltfpack quantizes positions and texture coordinates using
integers; this results in very small scaling values that are required to
transform the values back into 0..1 range.
While this is generally not a problem, there are some contexts in which
the scale values are too small and may be truncated to 0, eg if the shader
is using medium precision. Additionally, for native GPU backends like
WebGPU the shader may need to match the logical type of the vertex
attribute with the shader declaration - for unnormalized integers to
work, one must use i32/u32 types, which makes meshes that use …
> gltfpack: Implement support for normalized attributes

- gltf/basisenc.cpp
- gltf/fileio.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
When internal Basis encoding was implemented initially, Basis didn't
provide an API to compress multiple textures together in parallel, but
now it does.
Right now we rely on the gltfpack fork to provide a special performant
job pool implementation that allows us to scale parallel compression
much better. As a side effect, this means gltfpack *must* be built
against the forked version of basis_universal, which results in
confusion around builds.
The implementation of parallel_compress is inefficient in the main
version, but it's efficient in gltfpack fork. This change switches to
that API instead, with the eventual angle of integrating the efficiency
improvements into mainline so that we no longer need to maintain a fork.
Before this change we would read the images in parallel, but that …
> gltfpack: Switch to basis_parallel_compress

- js/index.js
- js/index.module.d.ts
- js/index.module.js
- js/meshopt_simplifier.module.d.ts
- js/package.json
Changes:
- Adds missing exports for MeshoptSimplifier
- Fixes typo in TypeScript type declarations
- Changes `[Flags]` to `Flags[]`, allowing empty array
> Adds exports and updates type definitions for MeshoptSimplifier

- src/vertexcodec.cpp
- tools/movemask.smt2
Instead of using horizontal adds or more expensive paired adds on 32-bit ARM,
we can use the same trick we use for Wasm which assumes that all input
components are 32-bit and uses a specially crafted constant to turn the result
into a bitmask.
This results in ~2% faster decoding on Apple M2; the performance will need to
be validated on other ARM CPUs.
> vertexcodec: Use a more efficient lowering for neonMoveMask

- js/meshopt_decoder.js
- js/meshopt_decoder.module.d.ts
- js/meshopt_decoder.module.js
This change implements support for using WebWorkers during mesh
decoding; MeshoptDecoder module now has a function, useWorkers, that -
when called - switches behavior of the new function
decodeGltfBufferAsync to use web workers.
decodeGltfBufferAsync can also work without web workers, and it doesn't
require the use of ready promise, which simplifies support in GLTF
loaders.
> js: Implement support for WebWorker-driven decoding

- .github/workflows/build.yml
- .github/workflows/release.yml
- Makefile
Now we can point WASI_SDK to an actual SDK install (using Ubuntu packaging structure).
> Clean up build infrastructure around Wasm

- gltf/gltfpack.cpp
Specifying -te did nothing for 2 years now (since 0.15); it looks like
the mere presence of the option now generates some confusion (#459), so
this change simply removes it for the future release.
> gltfpack: Remove dummy -te option

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/stream.cpp
- gltf/write.cpp
- src/vertexfilter.cpp
Currently gltfpack provides all or nothing quantization: either all
attributes get quantized, or none do.
When quantization is used, we use the most size and memory efficient
formats, which is great, but it can lead to integration issues for
applications - since dequantization uses an extra transform, this
results in changes that are needed for some applications to take that
transform into account. Notably, these changes mostly revolve around
positions (and rarely around texture coordinates wrt texture
replacement, but positions are definitely the main source of issues).
Due to the flexibility of meshopt codecs however, there are other
options available that don't change the coordinate space of mesh
positions, but instead just change the positions a little bit to encode
more efficiently. …
> gltfpack: Experimental support for floating point position quantization

- src/clusterizer.cpp
- src/indexgenerator.cpp
- src/meshoptimizer.h
- src/overdrawanalyzer.cpp
- src/overdrawoptimizer.cpp
- src/simplifier.cpp
- src/spatialorder.cpp
This change removes references to glVertexPointer from comments and
clarifies that stride must be greater or equal to size for each stream.
Additionally, for every function that takes position stride and expects
to read 3 coordinates from it, we now assert that the stride is at least
12 to prevent accidental misuse.
Fixes #463.
> Clarify stride in documentation / asserts

- gltf/gltfpack.cpp
Right now specifying -vpi does nothing compared to the default options,
but it might become useful if we decide to change the default to -vpf
> gltfpack: Add -vpi option to match current default

- .github/workflows/build.yml
- .github/workflows/release.yml
With this change we no longer build anything for .md changes to make
sure we don't waste build capacity, and don't build release action on
PRs - instead we add a simple build to validate that gltfpack builds in
Basis mode to build.yml to prevent regressions.
> Reorganize builds a little bit

- src/vertexcodec.cpp
This redundantly recomputes the number of sentinel elements in the
source byte group using scalar arithmetics exclusively; the general
strategy is to put 0 or 1 into each nibble, and then add them all into
the top nibble using a 64-bit multiply + shift. The sum doesn't overflow
because mode1/2 would never be used when all elements are sentinel,
since mode3 is always picked in these cases as it's shorter.
The reason why this helps is that the computation is shorter
(latency-wise) than the actual decoding that uses SIMD, and this allows
the CPU to overlap the decoding of consecutive byte groups.
This may regress throughput on in-order CPUs but should be generally
beneficial on CPUs where vector and scalar instructions can co-issue
with a reasonably wide window.
Based on suggestion by …
> vertexcodec: Implement scalar compare+popcnt for SSE3/NEON

- extern/cgltf.h
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/json.cpp
- gltf/material.cpp
- gltf/parsegltf.cpp
- gltf/write.cpp
This change reworks cgltf parsing to handle extras by copying the data out of glTF file (upstream PR incoming), which removes the need for extras evacuation thereby simplifying the extras logic and making it easier to extend the pipeline to add extras handling for elements that currently don't preserve these.
> gltfpack: Simplify extras handling

- CMakeLists.txt
The `_mm_undefined_si128()` AVX-512 intrinsics on GCC produces an "uninitialized variable" warning (which is, well, what is it intended to actually do), and due to `-Werror` that makes the code not compile even though there's no actual error inside your code. I discovered this only because I use `-march=native` to build my system packages and recently upgraded to an AVX-512-equipped hardware.
For completeness, here's the full error message (compiling 0.18, but same happens in current `master`):
```
/usr/bin/c++ -DMESHOPTIMIZER_API="__attribute__((visibility(\"default\")))" -Dmeshoptimizer_EXPORTS  -march=native -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -O3 …
```
> Don't add -Werror on GCC, it can break compilation in certain cases

- .github/workflows/build.yml
- .github/workflows/release.yml
- CMakeLists.txt
We now enable warnings as errors in CI CMake builds only using a new MESHOPT_WERROR option; this ensures that while configurations tested in CI are warning-free, meshoptimizer can be used on an untested compiler version without errors.
For simplicity, Makefile builds for now keep -Werror unconditionally since these would mostly be used during meshoptimizer development.
Foillowup for #486
> By default, don't treat warnings as errors in CMake builds

- gltf/write.cpp
While compressing with gltfpack, skin names aren't saved.
> gltfpack: Save skin names

- gltf/basisenc.cpp
- gltf/fileio.cpp
- gltf/gltfpack.h
On Windows, our implementation of TempFile class implicitly relied on creating the files to get unique names, because that's what _mktemp does. When using parallel compression API, we pre-create all temp file names ahead of time and as such we accidentally got the same output temp file name, which resulted in broken compressed results.
To avoid issues with various temp file APIs we simplify the code by manually constructing temp file names from image index and PID-based temp prefix.
Fixes #507.
> gltfpack: Fix Basis encoding on Windows due to temp file sharing

- demo/main.cpp
- src/clusterizer.cpp
- src/vcacheoptimizer.cpp
When a meshlet is full, the triangle we've selected starts the new meshlet.
That triangle has most often been selected using meshlet scoring based on
size and cone - however, these are in relation to the old meshlet that the
new triangle doesn't relate to.
This change replaces the scoring criteria for cases like this with topological
criteria based on number of outstanding triangles in the proximity. We want to
start with triangles that have the smaller number of live neighbors because
otherwise we're more likely to leave small isolated islands of triangles which
ends up increasing the meshlet size.
This change ends up reducing the number of meshlets by 1-2% and reducing the
mean size of a meshlet by up to 5%, yielding slightly more optimal output for
roughly the same build cost (since we …
> clusterizer: Improve selection critera of first triangle of new meshlet

- js/meshopt_simplifier.js
- js/meshopt_simplifier.module.js
When computing the number of vertices, we took the length of the Float32Array without accounting for the stride. This would typically result in 3-4x higher value that's being passed in, which would significantly increase the memory consumption during simplification, as the array of quadrics would be much larger than it needed to be.
> js: Fix significant memory overallocation for simplify

- src/vertexfilter.cpp
Instead of using specific clang version detection for the intrinsic, we use a more general __has_builtin check. Note that the presence of this construct can not be checked in the same preprocessor expression so we use a standard (if perhaps rude) trick of re-defining __has_builtin if absent.
Fixes #534.
> vertexfilter: Fix build on Android NDK 19c

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
Locking border vertices may be useful to preserve geometric details in certain cases. This helps when the mesh is split into multiple chunks (especially if the splitting is based on material since gltfpack won't be able to merge the sub meshes before simplification), or on certain classes of 3D scanned meshes when triangles are covering gaps in geometry without being connected to anything.
This setting is opt-in as it regresses simplification quality in cases when the locking isn't required; for some applications it's a safer default though so they can choose to enable -slb always.
Fixes #518.
> gltfpack: Enable border locking during simplification if requested

- gltf/material.cpp
If a material has both a metallic-roughness model and a specular-glossiness model, optimizeMaterials only checks the metallic-roughness model, which makes it incorrectly set the alphaMode to OPAQUE. This PR fixes the bug by checking both shading models instead of the first available model.
> gltfpack: Fix optimizeMaterials incorrectly optimizing on MR fallback

- src/vertexcodec.cpp
If compiling a project with wasm simd and the auto vectorization flags of compiler it broke compilation
As emscripten also support  simd intrinsics compilation to wasm simd, the current set of flags are not compatible, ending breaking compilation.
(when compiling meshoptimizer as part of a bigger codebase, not when compiling it as a library)
> Allows both "wasm simd"  in meshtopt and "simd intrinsics" elsewhere

- src/vertexcodec.cpp
When Wasm SIMD spec was finalized, the SIMD intrinsics in LLVM got renamed to match the spec. This change happened in LLVM 13; the old intrinsics emit deprecation warnings.
Since it's been two years and we're now on LLVM 15 in the official builds, it's probably time to clean up the code and switch to new intrinsic names. If we need to we can add stubs for LLVM 12 separately; this only affects builds that explicitly target Wasm SIMD so that is unlikely.
Also, we don't need to disable unused variable warning since we can just remove the variables that were never used to begin with.
> vertexcodec: Clean up Wasm SIMD implementation

- .github/workflows/build.yml
- .github/workflows/release.yml
This should fix build-time warnings on GHA about Node 12 deprecation.
> Update versions of setup-node and upload-artifact

- extern/cgltf.h
bufferView is not a valid attribute. We will reject scenes like this based on presence of the required extension, but we still need to have the parser bug fixed.
> gltfpack: Fix loading scenes with EXT_mesh_gpu_instancing

- src/vertexfilter.cpp
There was a missing undef of SIMD_SSE when we detect we're using __wasm_simd128__ in vertexfilter.cpp, funny enough vertexcodec.cpp does do this correctly.
Either way, this change fixes the WASM target compiling.
> Fixed vertexfilter.cpp compilation with Emscripten

- extern/cgltf.h
- gltf/parsegltf.cpp
This is mostly focused on cgltf_accessor_unpack_floats, but also adds a counterpart cgltf_accessor_unpack_indices.
The optimizations reduce the overhead by extracting some common code out of the per-element loop, and also implementing a fast path for direct memcpy. Without the fast path, this results in ~10% faster glTF parsing (tested end-to-end on Amazon Bistro exterior scene); with the fast-path, this makes the parsing 1.5x faster. Note that the time includes loading gltf/buffer data from files and other processing gltfpack performs to load the data into memory.
> gltfpack: Optimize data extraction from glTF files

- src/indexgenerator.cpp
When vertex_size is small, the memcpy dispatch overhead is significant and it dominates the cost of the copy loop. To avoid this, we specialize the loop for a few common sizes, mostly focusing on deinterleaved streams as this is where the overhead is highest. More vertex size specializations can be added in the future if requested.
For gltfpack, this results in ~5% speedup on end-to-end processing of geometry heavy scenes like Amazon Bistro. meshopt_remapVertexBuffer sees a ~4x speedup in isolation.
> indexgenerator: Optimize meshopt_remapVertexBuffer for deinterleaved streams

- gltf/library.js
`Uncaught SyntaxError: Unexpected strict mode reserved word (at library.js:50:3)`
raises while loading 'library.js' as external js module.
> avoid to use reserved word 'interface'

- gltf/gltfpack.h
- gltf/parsegltf.cpp
- gltf/stream.cpp
- gltf/write.cpp
This change keeps attributes `_ID`, `_BATCHID` and `_FEATURE_ID_*` in tact when processing the scene. We assume that these attributes are scalar and encode them as floating-point (to avoid possible range issues with uint16).
This change is similar to #530 (without the extraneous names) but it crucially limits the supported attributes by name otherwise we can not assume that the attribute is scalar or integer, whereas with this filtering the assumption is reasonably safe.
For increased compression efficiency, when `-cc` is applied we use exponential encoding unless the IDs exceed the maximum permissible range. On some test files that use feature and vertex ids, this reduces the compressed size of ID attribute streams by ~2x.
Relates to #165
Fixes #529
Closes #530
> gltfpack: Preserve custom ID attributes

- gltf/README.md
The -te flag was removed a few versions back, but it was still mentionned in the readme.
> Update README.md to remove mentions of -te option

- .github/workflows/build.yml
If this is faster we could probably just switch from -Models to -Assets.
Also bump validator to release 2.0.0-dev.3.8
> Add glTF-Sample-Assets based gltfpack test

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/stream.cpp
Similarly to position quantization, we can use quantized floating point values to represent texture coordinates. This can be useful as it trades off a little bit of memory and compression efficiency for convenience and interoperability - without the use of texture transforms it becomes easy to swap textures, reuse materials, and avoid edge cases in quantization when UV bounds are very large.
While `-vtn` option is currently not very useful as it just enforces the default, in the future we could ostensibly automatically switch between normalized integers and floating point based on some heuristics around UV range.
Fixes #194
Fixes #574
> gltfpack: Implement support for floating-point texture coordinate quantization

- extern/fast_obj.h
- gltf/parseobj.cpp
When the source .obj file carries color data, we now preserve it when processing glTF files.
Example (https://www.shapeways.com/forum/t/vertex-color-obj-format.42061/):
Note: some .obj files may have redundant .w component, which gets translated as red color:
```
v 3.25000 -2.48000 14.0000 1.00000
```
Only one file in my test data set has this so for now we will assume these are broken.
> gltfpack: Implement support for extracting colors from .obj files

- extern/fast_obj.h
Some .obj files have extra whitespace after usemtl and other statements; this may interfere with parsing, for example by adding a space to the material name which can result in inability to find it in .mtl file.
Fixes #590
> extern: Fix fast_obj to trim trailing whitespace for names

- gltf/gltfpack.h
- gltf/parseobj.cpp
When parsing .obj, gltfpack now:
- Preserves material names
- Preserves object names by parsing individual objects separately and assigning them to separate nodes
- Preserves Kd/d material parameters
- Fixes texture paths if they contain backslashes in the source .mtl
- Assigns the default scene in the output .glb file
Before merging:
Fixes #594 
Fixes #595
> gltfpack: Enhance .obj parsing by preserving more information

- CMakeLists.txt
- README.md
- demo/tests.cpp
- src/meshoptimizer.h
- src/quantization.cpp
- Move larger quantization functions to a .cpp file to make sure we can add more advanced quantizers in the future without inflating the header size
- Add `meshopt_dequantizeHalf` which can be used to reverse float->half quantization in cases when the result is needed on the CPU
- Document manual dequantization process a little better
Fixes #597.
> Improve quantization utilities

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/material.cpp
- gltf/write.cpp
Blender glTF exporter (and possibly others) output duplicate texture objects in some exports. This blocks material merging which can result in more draw calls than necessary, and in some loaders (such as Three.JS) may result in extra texture decoding during loading and extra memory spent.
For simplicity we still assume that images and samplers in the source document are unique, but deduplicate and remove redundant texture objects now.
The process is a little different from how materials are deduplicated, as we need to maintain remap for unused textures to avoid traversing all texture views again as they are part of a complicated material structure.
> gltfpack: Merge identical texture objects together

- gltf/node.cpp
We accidentally computed scale using columns instead of rows, which led to rotation affecting scale for non-uniform scale factors.
The adjusted implementation has been validated against cgltf node->matrix function and appears to round trip within floating point precision and modulo redundancy wrt scale sign that is inherent during reconstruction.
This fixes mesh instancing for scenes with non-uniform scale & rotation.
> gltfpack: Fix row vs column indexing in decomposeTransform

- gltf/mesh.cpp
Before we were able to merge meshes when they were parented to the nodes with the same transform (or rather nodes without transform parented to the same node), but when instancing was enabled, we'd gather instances and then refuse to merge the resulting meshes.
Normally this isn't a problem as usually mesh merging works for single meshes, but this can impact instancing efficiency for structured scenes.
On one test scene, this results in a significant reduction of draw calls:
- Default: 753 draw calls
- Instanced, before this patch: 2645 draw calls
- Instanced, after this patch: 105 draw calls
> gltfpack: Merge instanced meshes when instance transforms align

- demo/tests.cpp
- js/meshopt_simplifier.test.js
The collapse order in our test isn't very well specified, as such under different compilers and floating point configurations we may end up with a different quad triangulation.
For now let's attempt to fix this by perturbing pos.z which seems to fix the issue at least on Xcode/A64.
> Stabilize simplifyWithAttributes tests by adjusting pos.z

- js/meshopt_decoder.js
- js/meshopt_decoder.module.js
Terser minifies and mangles JS; since we build WebWorker JS code dynamically as a string, references to identifiers from that string end up being invalid.
To reduce fragility of this code, we no longer rely on module-scoped variables instance and ready, and instead communicate the instance through self.ready promise.
See #609.
> js: Update decoder module to be more friendly to Terser

- .github/workflows/build.yml
For now we only run with `-cc`; this means that some paths will not be adequately covered. Additionally, some extensions may not be covered if glTF-Sample-Assets has no examples with them in use.
> Add coverage build for gltfpack

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
- gltf/write.cpp
Previously, when targeting .gltf files without texture compression, gltfpack left texture URIs untouched in the file. This meant that the users were required to copy the texture files by hand to the output folder so that the textures could be discovered (or somehow reference the original folder in the loader).
When using texture compression, gltfpack would instead save the files into the output folder. This meant that the output glTF file was complete, however when some textures were compressed and some weren't using selective (slot-specific) compression, this still meant that some files needed to be copied by hand.
When targeting .glb files, all textures we embedded in the output, compression or not. So the only way to guarantee complete glTF output was to use .glb destination... …
> gltfpack: Improve texture file handling behavior

- gltf/animation.cpp
Before this change we evaluated translation using the node's scale, even though the node's own scale gets ignored when transforming the node's translation.
This could lead to issues where gltfpack would ignore the translation animation in nodes with very small scale even though the parent's scale was reasonable and the translation was noticeable as a consequence.
Fixes #615
> gltfpack: Evaluate translation error relative to parent node scale

- gltf/mesh.cpp
A fair amount of point cloud exports to glTF seem to have a redundant
normal stream (filled with the same value). This is relatively common
(about one in 6-7 files from Sketchfab has this issue), and it results
in incorrect rendering for renderers that respect normals *and* extra
data (4 out of 16 bytes in point clouds with normals & colors).
While it may sometimes be incorrect to remove this data, for now let's
err on the side of aggressive optimization and detect & remove it.
> gltfpack: Remove point normal streams when they are constant

- src/simplifier.cpp
While quadrics are very important for triangle mesh simplification, they
are decidedly overkill for point cloud simplification. We encode a
simpler function into them compared to triangles, and even that function
is too complicated for what we need - minimizing the sum of square
distances to all points in the cell ends up yielding approximately the
same result as averaging all points in the cell and minimizing the
distance to that average.
The benefit of a simpler formulation is that there's less memory used
for encoding the function and less computation required to aggregate the
points / minimize the error.
This also sets us up for including color error into the calculation (by
computing a weighted average of the colors and minimizing the 6D
distance to XYZ+RGB). Even once we include RGB …
> simplify: Rework point simplification to use reservoirs

- demo/main.cpp
- demo/tests.cpp
- gltf/mesh.cpp
- src/meshoptimizer.h
- src/simplifier.cpp
Following the new reservoir code, we can now easily accumulate colors into the reservoirs, and add the color error to the position error with a user-supplied weight. The color error is squared distance; as such, we scale it by the squared weight.
In addition, we now use color alpha as a point weight; the weighted sum will thus bias towards more opaque points.
Note that the alpha is not accounted for during point selection.
> simplify: Add color support to simplifyPoints

- gltf/gltfpack.cpp
- src/indexcodec.cpp
indexcodec 0 is a legacy version that should not be preferred to 1 in any way; applications that worked with glTF contents as well as applications that required superior compression all had to set it to 1 manually.
We now bump the default encoding version to 1, which should be decodable by any application that uses meshoptimizer 0.14 (released 3 years ago) or later.
For applications that need compatibility of binary data here it should be trivial to revert back to 0.
For now we keep explicitly setting the versions for data encoding for gltfpack and JS mesh encoder; it's very unlikely that a newer version of index codec will be introduced, but a newer version of vertex codec is possible, so we'll keep pinning the version for glTF content for now.
> indexcodec: Bump default encoding version to 1

- gltf/basisenc.cpp
- gltf/gltfpack.cpp
- gltf/image.cpp
- gltf/mesh.cpp
- gltf/parsegltf.cpp
- gltf/parseobj.cpp
- gltf/write.cpp
- src/indexgenerator.cpp
- src/meshoptimizer.h
- src/simplifier.cpp
- src/vertexcodec.cpp
Note that we previously used 0/nullptr/NULL in gltfpack in different
places. and 0/NULL in meshoptimizer in different places.
gltfpack is C++11 but since it's developed alongside meshoptimizer
which doesn't currently require C++11, for now we use NULL for
consistency instead of nullptr.
> Use NULL for null pointer constants instead of 0/nullptr

- demo/simplify.html
- js/meshopt_simplifier.js
- js/meshopt_simplifier.module.d.ts
- js/meshopt_simplifier.module.js
- js/meshopt_simplifier.test.js
Both functions are marked as experimental in C++ code; their interface and implementation is subject to change. In JS, if the interface of these functions changes, it may lead to subtle or not-so-subtle issues with these functions. For now we require the caller to opt into the use of these functions by setting a module-level experimental boolean.
I am not 100% sure this is a great idea :) but the sensible alternative seems to be just marking them as experimental in the documentation... I mainly would like to avoid the situation where the NPM update to a future version silently breaks the users who decided to rely on the specific behavior of these functions. simplifyPoints is not very likely to change but is relatively new, and simplifyWithAttributes is very likely to change in so far as …
> js: Mark simplifyWithAttributes and simplifyPoints as experimental

- js/meshopt_decoder.js
- js/meshopt_decoder.module.js
Before this change, calling useWorkers twice would allocate new workers but keep old workers around; this resulted in old workers leaking when the new count was larger; when the new count was smaller, we would still maintain the worker count but recreate some workers and leak older ones.
Instead we now only create more workers if more workers are requested, and if the requested count is smaller than current worker count, we ask some existing workers (nicely) to close by sending a dummy message.
Because messages are processed in order, and processing the worker response does not access global workers[], it should be safe to call useWorkers(0) at any point without disrupting already dispatched requests. This also provides a clean way to reclaim all resources used by the workers, including …
> js: Properly manage workers when useWorkers is called twice

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/material.cpp
- gltf/mesh.cpp
Unlit materials do not require normals or tangents; we already automatically filter out tangents because of the lack of normal texture or other material extensions, but normals were not removed until now.
This can reduce the amount of geometry we need to output; this also mostly subsumes the redundant normal stream filtering for point clouds as point clouds often have an unlit material, but for now we'll keep that redundancy.
When material variants are used, we only do this when all material variants for a given mesh are unlit. The use of the default material also blocks this optimization as default material implies basic lighting.
> gltfpack: Remove normal streams from meshes with unlit materials

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/stream.cpp
Usually normalized integer storage is optimal for normals; however, morph target deltas require a [-2, 2] storage range. During quantization we clamp them to [-1, 1] which ends up usually working fine, however there are some use cases where this doesn't work well when the normal deformation is extreme.
This can be solved by scaling normals by 0.5, so we'll use [-0.5, 0.5] range for base normal and [-1, 1] range for normal deltas. This usually works fine with any glTF renderers as they normalize the normal (which is more or less required for handling non-uniform scale transforms).
However, the validator treats files like this as invalid. Validator doesn't process files with -c/cc so technically we could fix this when compression is enabled, but that would result in an odd mismatch where …
> gltfpack: Introduce optional floating-point normal quantization

- src/vcacheoptimizer.cpp
Auxiliary buffer `live_triangles` isn't required for `optimizeVertexCacheTable` variation.
As adjacency list `counts` is also decreased when necessary, and can be correctly used in every required instance.
> optimizeVertexCacheTable: redundant connection count buffer 

- src/vcacheoptimizer.cpp
gcc/clang lower the condition to cmov sequence but MSVC uses branches
here; it's important to use branchless lowering as these branches are
difficult to predict. This change makes optimizeVertexCache ~7% faster
on MSVC on large meshes.
> vcacheoptimizer: Tweak condition to help MSVC generate branchless code

- extern/fast_obj.h
- gltf/parseobj.cpp
This can happen in multiple different ways:
- No mtllib reference in the .obj file
- mtllib reference in the .obj file that can not be loaded
- usemtl references to materials that don't exist in the mtllib
Fixes #640
> gltfpack: Warn when some materials could not be loaded from the .obj/.mtl

- extern/cgltf.h
- gltf/README.md
- gltf/gltfpack.cpp
- gltf/material.cpp
- gltf/write.cpp
This change adds cgltf parsing support as well as material merging/writing; this extension is similar to KHR_materials_ior in that it's just one extra float.
Specification:
https://github.com/KhronosGroup/gltf/tree/main/extensions/2.0/Khronos/KHR_materials_dispersion
> gltfpack: Add support for KHR_materials_dispersion

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/write.cpp
This change consolidates error handling for images that can't be read, written, or encoded, and uniformly emits an invalid embedded Base64 URI in these cases.
This keeps the file invalid as per glTF spec, but allows various loaders to load it. The source file in cases like this was semantically invalid so maybe this is fine.
Ideally we would probably want to remove references to the image. Unfortunately, to preserve glTF file validity, this requires transitive removal of texture references from all materials as well as image/texture array compaction...
Fixes #675
> gltfpack: Replace images that can't be found or encoded with invalid URI

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
When -sv command line argument is specified, we will use vertex colors
or vertex normals as part of attribute aware simplification to produce better
results. For now the intention is to use a single argument to
incorporate multiple different types of attributes with fixed weights,
in the future we might expose more detailed control via '-sv?' prefix.
Fixes #652
> gltfpack: Use vertex attributes to guide simplification

- .github/workflows/build.yml
- gltf/README.md
- gltf/parsegltf.cpp
When the input file contains EXT_meshopt_compression encoded buffer
views we can now decompress them and process the data as usual. This
should help with interoperability.
If the input uses filters, decompression and recompression  may
introduce extra precision issues; this is mostly captured by an existing
quantization warning though.
> gltfpack: Implement support for EXT_meshopt_compression inputs

- gltf/README.md
- gltf/basisenc.cpp
- gltf/gltfpack.cpp
- gltf/image.cpp
- gltf/material.cpp
- gltf/parsegltf.cpp
- gltf/write.cpp
When the input file has KHR_texture_basisu extension, we now will
preserve the images along with the extension in the output file instead
of discarding it.
When `-tc` is specified, images like this will not be recompressed; accordingly,
some flags like `-tl` and `-tp` will not work with pre-compressed inputs.
When the input textures specify both uncompressed and compressed image,
the behavior is likely to be suboptimal...
Fixes #537.
> gltfpack: Implement support for KHR_texture_basisu inputs 

- .github/workflows/build.yml
- gltf/material.cpp
There are some cases when the texture refers to a NULL image, eg when an unknown image extension is used such as EXT_texture_webp. In this case we used to remove UV coordinates which triggered excessive validation errors; we now preserve UV coordinates even though the texture object is not fully serialized/processed.
> gltfpack: Preserve mesh attributes if the texture exists with no image

- extern/cgltf.h
- gltf/README.md
- gltf/gltfpack.cpp
- gltf/parsegltf.cpp
When -mi is not specified but the input scene has instancing extension,
we convert the instances to the internal world-space transform
representation, which can then be serialized using our existing code.
Note that instances are not attached to nodes in the internal
representation; animation and scene data is thus silently discarded for
now. This is not ideal but is not trivial to change as it would require
reworking other parts of the processing pipeline. This also means that
the relationship between named nodes and instances isn't preserved,
and instances for a given mesh are always concatenated - which is good
for efficiency (assuming per instance culling) but may restrict some
use cases.
Fixes #685.
> gltfpack: Implement EXT_mesh_gpu_instancing support for input scenes

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/stream.cpp
- gltf/write.cpp
If the input model is already quantized with the same settings wrt
position encoding, then the computed quantization parameters result in a
no-op transform (offset 0, scale 1). However, repeat invocations of
gltfpack will each add one extra node with a no-op transform. With this
change, if we can afford to attach the mesh directly we will do so.
Note that in the future, we could also merge node transforms via the
hierarchy, but that should be a separate optional optimization as it can
interfere with application processing logic.
> gltfpack: Attach meshes directly to nodes when quantization is a no-op

- extern/fast_obj.h
- gltf/parseobj.cpp
fast_obj 1.3 makes a change to internal data structures to use indexed
texture objects; as such the .obj material parsing code had to be reworked
to accommodate that.
> gltfpack: Update fast_obj to 1.3

- demo/main.cpp
- demo/tests.cpp
- js/meshopt_simplifier.js
- js/meshopt_simplifier.module.d.ts
- js/meshopt_simplifier.module.js
- src/meshoptimizer.h
- src/simplifier.cpp
When simplifying a small subset of the larger mesh, all computations
that go over the entire vertex buffer become expensive; this adds up
even when done once, and especially when done for every pass. This
is a critical part of some workflows that combine clusterization and
simplification, notably Nanite-style virtual geometry renderers.
This change introduces a sparse simplification mode that instructs the
simplifier to optimize based on the assumption that the subset of the
mesh that is being simplified is small. In that case it's worth spending
extra time to convert indices into a small 0..U subrange, do all
internal processing assuming we are working with a small vertex/index
buffer, and remap the indices at the end. While this processing could be
done externally, that is less …
> Improve support for cluster simplification

- extern/cgltf.h
- gltf/README.md
- gltf/gltfpack.cpp
- gltf/image.cpp
- gltf/material.cpp
- gltf/write.cpp
Similarly to KHR_texture_basisu appearing in the input, we now preserve
WebP images along with the extension if they are present in the input
file. There is no support for encoding them if the input file uses PNG/JPEG
(nor will there be).
Relies on https://github.com/jkuhlmann/cgltf/pull/253 for parsing.
Fixes #536.
> gltfpack: Add support for EXT_texture_webp

- src/simplifier.cpp
Instead of checking if the dot product is 0 or negative (90 degree limit on triangle rotations), use a cutoff of ~75 degrees. The motivation here is that meshes with complex curvature can end up flipping triangles through a series of collapses, and since we always evaluate flips compared to the current mesh we miss that. Technically this can happen even with a 75 degree limit, but in practice this solves cases of flips that have been reported before, and doesn't noticeably constrain simplification or slow it down.
For numerical stability, we avoid dividing by the triangle areas (as they can be close to zero) and instead use the areas to compute a bound for dot product. Even if the area product underflows, we just get the same check that we used to have -- areas should be in [0..1] so …
> simplify: Make hasTriangleFlip predicate use an angle cutoff

- gltf/gltfpack.cpp
- gltf/gltfpack.h
When a new option `-kv` is specified, gltfpack no longer removes unused vertex attributes (v mirrors existing usage for -sv and -vX).
This can be useful in a few cases:
- Normals may be needed for custom vertex processing even if materials are unlit
- Tangents may be needed for custom shading at runtime that gltfpack isn't aware of
- Tangents may help with simplification across UV mirroring seams
- Texture coordinates may be needed at runtime even if this is not indicated by any material textures; in this case, -vtf should be used to disable UV quantization
Fixes #715.
> gltfpack: Optionally keep unused vertex attributes

- gltf/mesh.cpp
- src/simplifier.cpp
We have been relying on smuggling the kind/loop info computed during
classification via meshopt_simplifyDebug global pointers. This
information is valuable to visualize, and there's future improvements to
classification that would need to be debugged, so it's not ready to
remove but exposing this as globals results in issues as it expands the
exported API surface, making it different between release & debug builds.
Instead, this change adds a way to request this via an option bit, and
return it via indices[] - instead of per-vertex information, we return
this per-triangle-corner. This fixes all the issues with exported symbols,
and even makes the information available to JS (the size overhead is
insignificant) if we decide to use simplify.html for visualization.
The newly added option bit …
> simplify: Rework internal debug visualization code

- gltf/gltfpack.cpp
This results in some meshes migrating between scenes in case they were detached from their existing nodes.
Fixes #723
> gltfpack: Do not merge mesh primitives with different scenes

- CONTRIBUTING.md
Add a section to contributing guide regarding the agreement to distribute the code under the terms of MIT license and transfer various rights to the project maintainer.
Prior art (using the same language):
- https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING.md#copyright--contributor-license-agreement
- https://github.com/ocornut/imgui/blob/master/docs/CONTRIBUTING.md#copyright--contributor-license-agreement
This change naturally does not retroactively affect existing contributions (although the first paragraph is partially established by [GitHub Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license)); the vast majority of the code is written by the project author anyway so this should not …
> Update CONTRIBUTING.md with contributing agreement

- README.md
- demo/main.cpp
- demo/simplify.html
- demo/tests.cpp
- src/meshoptimizer.h
- src/simplifier.cpp
The goal of this set of changes is to bring the attribute metric closer to its ideal state by validating and refining the math and improving the weighting logic to make the error more composable and explainable.
The main user-visible change here is the switch to unnormalized area weighted quadrics; detailed reasoning is provided in 9efadb015bb3c9dcd1201771405bb81c8bfb6908 but the high level summary is that this makes the error closer to the ideal "distance traveled by the vertex times the attribute deviation" (squared) which results in a better match between (normalized) position and attribute metrics, making adding them more sensible, makes attribute weight tuning more intuitive and mesh scale-invariant, and makes the error limit and resulting error actually useful for LOD selection and …
> simplify: Improve attribute metric computation

- demo/simplify.html
- js/meshopt_simplifier.js
- js/meshopt_simplifier.module.js
This change adds statistics and debug overlays with information that is important for simplification debugging; the demo program is used to develop simplification algorithms further, so these additions should make future updates to simplifier easier. 821399cc4b6c9ff82ece75161249cf40165d4f77 was also meant to be part of this PR but was accidentally committed directly to master.
For increased iteration speed this also adds auto-update mode that, combined with running `while true; do make js WASI_SDK=$WASI_SDK; sleep 1; done`, creates a hot reload environment for C++ module.
Finally, this also adds an optional vertex welder using three.js BufferGeometryUtils; this is not optimal (neither wrt performance nor wrt control over tolerances) but it's a valuable stop-gap to be able to simplify some …
> demo: Improve simplification demo visualization

- .github/workflows/build.yml
- .prettierrc
- demo/index.html
- demo/simplify.html
- gltf/library.js
- js/meshopt_simplifier.js
- js/meshopt_simplifier.module.d.ts
- js/meshopt_simplifier.module.js
This makes sure that the main library code is ES5 compatible and ES6 features aren't used accidentally.
As part of this, Prettier settings were changed to format code with ES5 compliant trailing commas; this was a regression that didn't make it into any versioned builds.
> Add ES5 validation

- demo/tests.cpp
- src/simplifier.cpp
Initial implementation of attribute metric used the same indexing that
we use for positional quadrics, where multiple vertices with the same
position are collapsed into a single element. This is correct and
optimal for positions, but results in problems for attributes when the
vertex is on a seam: two associated vertices carry very different
attributes, and evaluating any attribute against a vertex from an
opposite side of the seam results in a large error. This results in a
suboptimal collapse sequence and an artificially inflated resulting
error.
This change fixes this by preserving the original indexing for attribute
quadrics and carefully aggregating these during collapses. For simplicity,
and because it does not seem crucial for quality, we still approximate
an error for one edge …
> simplify: Separate attribute quadrics on attribute discontinuities

- demo/tests.cpp
- src/simplifier.cpp
Instead of normalizing p10 we can correct the projection by the edge
length; since we normalize the vector anyway we instead scale p20 as
this avoids the need to handle singularity.
This makes the function a little faster; more importantly it reduces the
average error by ~1.5x (computed by comparing sqrt(quadric error) for p2
with the double precision distance-to-line computation)
> simplify: Minor improvements in quadricFromTriangleEdge

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
This change exposes simplification error via command line argument `-se`, which can be valuable to control simplification more precisely and may also be used to slightly increase the defaults when `-sv` is used.
Also this change completes https://github.com/zeux/meshoptimizer/pull/688 by incorporating both normals and colors when `-sv` is specified, which improves quality on models with vertex colors further.
Fixes #494.
> gltfpack: Improve simplification integration

- gltf/json.cpp
inf/nan are not valid in JSON syntax; while ideally we would not produce these values in the first place, it would make sense to have a last-resort check that outputs valid JSON regardless of the values.
For +-inf we clamp them to max float, preserving the sign; for NaNs we choose to output max float for now since that value is still valid in JSON but looks sufficiently weird that it's obvious something happened during processing.
Fixes #753.
> gltfpack: Sanitize floats before writing them to JSON

- demo/main.cpp
- demo/tests.cpp
- src/indexgenerator.cpp
- src/meshoptimizer.h
- src/stripifier.cpp
This PR implements a new algorithm, `meshopt_generateProvokingIndexBuffer`,
that can be used to generate a special index buffer along with a reorder table that
can be used to efficiently implement visibility buffer rendering using traditional
rasterization pipeline. It is based on [Variable Rate Shading with Visibility Buffer Rendering](https://advances.realtimerendering.com/s2024/index.html#hable)
(John Hable, SIGGRAPH 2024).
Without this, and without the use of mesh shaders, the applications that need to
output per-pixel primitive ID need to either use geometry shaders or unindexed
geometry (both lead to a significant slowdown) or access primitive ID in fragment
shader via `SV_PrimitiveID`/`gl_PrimitiveID` inputs. The latter seems tailor-made and
optimal, but unfortunately it triggers …
> Implement provoking vertex generation for visibility buffers

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
While reindexing full precision streams is usually sufficient to get a good non-redundant index buffer, some meshes go through export or processing pipelines that introduce imprecision in individual normals or tangents, creating artificial seams. This increases the storage size and decreases rendering efficiency, in addition to creating issues for simplification.
This can be solved with a tolerance-based weld pass, but for now we can simply use quantized normals/tangents during reindexing. Note that this by itself does not reduce precision of individual vertices, so in theory we can be *more* aggressive here with quantization bits - for now we always use 8 bits which should not cause issues even if the requested normal bits is 16.
> gltfpack: Use quantized normal/tangents for reindexing by default

- README.md
- src/meshoptimizer.h
- src/simplifier.cpp
Since the error for points is pos + color_weight * col, it is hard to
tweak color weight to be scale-independent. We had a similar issue in
the edge collapse metric, but here the issue is complicated by the fact
that it's incorrect to compute errors as pos * (1 + col), since multiple
points can have the same position but the color delta must be used for
picking the right replacement.
As a compromise, we scale the color weight by the grid scale; since the
maximum position error along any axis is the grid scale, this makes the
errors compatible, and makes it easier to tweak the weight: similarly to
edge collapse, a weight of 1 is a good default; at a weight of 1 a
distance of 1 in color is equivalent to a worst case positional delta,
so a point like this will only be selected if there is no …
> simplify: Adjust meshopt_simplifyPoints color errors to be more uniform

- CMakeLists.txt
- Makefile
- demo/main.cpp
- demo/nanite.cpp
This PR adds a new demo file, nanite.cpp, that implements Nanite-style hierarchical simplification.
Working off the SIGGRAPH presentation by Brian Karis, it builds a DAG of clusters; for each cluster,
it tracks the bounds and error that can be used to do LOD selection in parallel / independently at
runtime.
The goal of this code is *not* to be a production quality pipeline (yet!); it is to serve as a testing
ground for future improvements in meshoptimizer's algorithms as well as development of new
algorithms. In the future this may become a good starting point, but for now the main purpose
is to be a test harness, as such there's a bunch of statistics / visualization support code here (and
more to come in the future at some point).
Also, to have a reasonable baseline, this code integrates …
> demo: Initial hierarchical clustered simplification (Nanite) demo

- CMakeLists.txt
- gltf/gltfpack.cpp
- gltf/gltfpack.manifest
When main() is used, the inputs are ANSI according to the current code page; this is fine if the file paths can be converted to ANSI, but may fail to open some files and will use ANSI file paths inside .gltf files which violates glTF specification.
This can be worked around by using UTF8 as ANSI code page via a manifest; however, to avoid having to bundle a manifest we can also convert the command line arguments to UTF8 and set UTF8 as the codepage instead.
This requires Windows 10 1803; on earlier Windows versions setlocale should silently fail so this should be more or less equivalent to the previous code.
Fixes #767
> gltfpack: Use UTF-8 encoding during gltfpack processing

- demo/tests.cpp
- src/simplifier.cpp
In large meshes with complex topology we occasionally hit a case where
error_goal cutoff is not monotonic: a previous pass would simplify up to
a certain goal, but a subsequent pass would arrive at a smaller goal
(for example as invalid collapses get eliminated) and hit it before an
error that it already encountered.
If we already collapsed an edge with a given error it is always correct
to collapse other edges with a smaller error. This change tweaks the
conditional, which results in fewer passes on some meshes (e.g.
thai_buddha gets ~10% faster to simplify), 2-3% smaller error on some
meshes, and occasionally 1-2% larger error; most meshes simplify as they
did before however.
Additionally, this PR improves collapse sorting by making it a little more
precise at minimal extra cost; this …
> simplify: Avoid early termination of passes for complex meshes

- Makefile
- demo/simplify.html
- demo/tests.cpp
- src/simplifier.cpp
- tools/simplifyfuzz.cpp
While locked vertices can't move by themselves, ideally we should be
able to move any vertex into a locked vertex; currently this is allowed
for manifold but not allowed for border/seam. This artificially limits
the allowed collapses which can lead to larger than necessary result or
worse than necessary error as the simplifier is forced to consider edges
with worse error.
To enable border collapses, we simply need to extend the picking logic;
border-border edges are symmetric so it is enough to validate them in
one direction, but border-locked edges may be forward or backward (as
in, they may align with the topological edge direction or be opposite to
it), so we need to check loop or loopback depending on which vertex is
border.
Seam->locked collapses require special handling to discover …
> simplify: Enable border->locked and seam->locked collapses

- .github/workflows/build.yml
- Makefile
Warnings as errors interfere with local development, especially Wunused;
for CMake we already switched to specifying werror separately as an
option in #490, and it's probably time to do this for Makefile as well.
> Use -Werror in Makefile builds in CI only

- demo/nanite.cpp
This change mainly reworks cluster boundary locking to use explicit lock flags and reworks DAG build a little bit to allow for customizable group size with more careful checks. In addition, partitioning code is now correctly taking into account vertices with the same position, which strengthens adjacency between neighboring clusters, and switches to vertex adjacency for simplicity.
The larger group size allows much more freedom, as METIS would more often generate at least partially connected groups with a larger size (I also wanted to investigate recursive partitioning instead of k-way partitioning but since the goal isn't really to maximize METIS quality this is probably good enough for now). Together with more precise boundary detection, we can now get cliffs.obj (2M triangles) all the …
> demo: Miscellaneous improvements to clustered simplification

- demo/tests.cpp
- src/simplifier.cpp
In the previous implementation from #601, we would only read `vertex_lock`
data for the primary vertex (the vertex with the smallest index among those
with the same position). When using sparse mode, this would be the first
vertex referenced by the index buffer due to how the sparse remap works.
If the input locks were inconsistent between all copies, there could be
a situation where a vertex with the wrong index was asked to be locked,
and the vertex would still be not-locked and could move. When *not*
using sparse mode, this was particularly problematic as the flags would
be read from the vertex that might not be referenced by the index buffer
at all.
We now propagate the locked status into the primary vertex in a separate
pass; this requires re-locking the wedges in a separate pass, …
> simplify: Improve vertex_lock handling in presence of seams

- src/vertexcodec.cpp
- tools/codecfuzz.cpp
This change reintroduces TRACE macro to vertex encoder; we used to have tracing code but it was removed in 2020 as the v0 codec was finalized. However, in order to make progress towards v1 codec we need to bring some of it back; this change adds byte tracking back with a more concise but complete summary display, and also adds bit consistency tracking (a bit is considered consistent if it is the same as the last bit in the same position for the entire byte group). Bit consistency tracking helps analyze opportunities where rotation or reorganization of data can improve compression.
Note that tracing relies on global state and is not thread-safe; since it prints data to stdout it's not really useful in a threaded context either way, and the thread safety issues should not cause any runtime …
> vertexcodec: Reintroduce tracing and add roundtrip fuzzing

- src/simplifier.cpp
When attributes are incorporated into the metric, depending on the attribute weights we may see divergence between the error as returned by vertex quadrics alone and the result. Especially when the simplification does not have a set limit, this may lead to unexpectedly aggressive component pruning.
While ideally pruning should only be used with a reasonable error limit that negates these concerns, for now it is probably better to accomodate this use case by tracking the positional error separately.
To reduce the cost of tracking this error we recompute it as collapses are performed; this may seem counter-intuitive since we've already computed it during ranking, but conserving memory is more important here, and since we only need to do it when using attributes and only for collapses we end …
> simplify: Use error returned by vertex quadrics to guide pruning

- demo/main.cpp
- demo/nanite.cpp
While boundsError is an approximation and the precise version would compute the projected sphere bounds taking into account perspective distortion and near plane clipping, our simpler variant can work as well and is invariant to camera rotation which is a nice property in certain cases; for example in VR you might want to compute LOD based on a "third" eye, a center camera, so that the geometry is in sync between two eyes.
Our boundsError implementation was mostly serviceable but did not depend on camera field of view and had some potential issues with monotonicity for cases where the camera position was inside the sphere.
We now clip the distance to znear and properly scale it so that the result is a normalized screen space error (0..1, multiply by screen height to get pixels). This …
> demo: Improve boundsError to take camera parameters into account

- src/simplifier.cpp
Instead of updating quadrics as we are collapsing edges, we can update
them in batch after all collapses are done. This makes the code cleaner
since we do not need to replicate the collapse structure explicitly for
both remap and quadric update, and also makes it ~5-7% faster on large
meshes - presumably due to better data locality during the update.
The only subtle part here is vertex_quadrics update: we need to do this
just once, and we *know* the primary vertex will have to move if any
wedge moved, so we do that during the corresponding collapse. The
target vertex may not have had any collapses to the primary vertex in
case some vertex gets collapsed into a locked vertex.
This change results in exactly identical output; in the future, this
would result in a more careful handling of …
> simplify: Split quadrics update into a separate function

- gltf/gltfpack.cpp
- gltf/mesh.cpp
While on most scenes our strategy performs reasonably well, and we
already have some potential N^2 processing elsewhere, there are cases
where the existing N^2 algorithms in the pipeline are actually
semi-linear, because mesh merging lazily and effectively aggregates most
meshes; since deduplication is the first pass, it may actually be
quadratic in the face of a scene with a lot of meshes.
A simple fix is to track the number of occurences of each hash and only
search for duplicates for meshes where this value is >1. We could of
course implement more involved tracking but for now this works just
fine.
We also now prune the node list to avoid accidental duplicate attachments,
as it confuses the logic downstream in the pipeline.
> gltfpack: Accelerate deduplication pass for scenes with a lot of primitives

- js/meshopt_simplifier.js
- js/meshopt_simplifier.module.d.ts
- js/meshopt_simplifier.module.js
- js/meshopt_simplifier.test.js
This code never worked if an actual array was passed in as it required an element per float instead of an element per vertex.
Since we need to change this anyway, change the interface to accept Uint8Array instead of a boolean array. This is more consistent with other parameters and allows an upgrade path if the C interface changes from "lock flags" to just "flags".
> js: Fix vertex_lock support for simplifyWithAttributes

- .github/workflows/build.yml
- gltf/basisenc.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/image.cpp
While we expose an ability to specify texture compression settings for each texture class separately, there's a significant quality and size gap between ETC1S and UASTC that doesn't have any middle-ground options.
In some cases, downscaling an UASTC texture looks much better than a full-resolution ETC1S; however, when ETC1S provides sufficient quality, this can in turn reduce the quality visibly.
This change makes it possible to adjust the tradeoff with more granularity by specifying texture scaling per-class; for example,
gltfpack -tu -tc color -ts attrib 0.75
... will use ETC1S for color textures at full resolution, UASTC for other textures (normal maps and attribute textures), but will further downscale attribute textures (roughness, etc.) to 0.75 x 0.75 of the original resolution …
> gltfpack: Allow per-texture-class control for texture scaling

- gltf/basisenc.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
Similarly to texture scaling, there are cases where setting individual
limits for different classes can be helpful. Using -ts works when the
input assets are known to have reasonable sizes (and allows to preserve
the size considerations for individual materials), but for a completely
arbitrary input, it can be helpful to enforce a lower limit for normal
maps or attribute maps when they use UASTC.
Follow up for #798.
> gltfpack: Allow per-texture-class control for texture limit

- demo/tests.cpp
- src/simplifier.cpp
- tools/simplifyfuzz.cpp
When collapsing seam->seam or seam->locked edges, we were assuming that the attribute error on both the primary edge and the seam pair is about the same. There are cases when this is not true; that leads to the collapse with an ostensibly low error significantly changing attribute appearance.
To evaluate the error, we need to use the same logic as we use during perform() to discover the seam pair, and use the accumulated error of the two for the attribute component. The earlier notes in the comments suggested max/avg would be appropriate, but accumulation is actually correct: each error is weighted in proportion to the adjacent triangle areas, and if the seam didn't exist at all, these errors would be naturally accumulated through quadrics accumulation. So even on seams where the edges …
> simplifier: Evaluate attribute error for both edges for seam collapses

- gltf/gltfpack.cpp
- gltf/mesh.cpp
When two triangles with reverse UV direction meet, an edge between them
needs to be a seam edge. This makes sure that UV does not degrade by
preventing the collapses that go across different UV directions.
Ideally this should be implemented inside meshopt library at some point,
but it requires a separate function and some way to make possibly-manifold
vertices "seam" which may run into issues with the seam handling logic.
So for now, pre-process the mesh by splitting vertices in gltfpack, and
remap triangles with negative UV area to use the newly created vertices.
The number of these vertices is generally low, so it only slightly limits
simplification.
For now we only do this when `-sv` is specified, as it requires analyzing
the attribute values.
Fixes #718 (for gltfpack. In the future …
> gltfpack: Introduce artificial seam edges on UV flips

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/material.cpp
- gltf/mesh.cpp
- gltf/parsegltf.cpp
- gltf/write.cpp
GLTF format allows extras in primitives, gltfpack ignore it and merge primitives even when extras are present and different.
Fix #808
> gltfpack: Take account of primitive extras

- extern/cgltf.h
- gltf/README.md
- gltf/gltfpack.cpp
- gltf/material.cpp
- gltf/write.cpp
Updates cgltf.h from a pending PR with support for the extension, and implements material merging/analysis/writing for the extra extension.
Specification:
https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_diffuse_transmission/README.md
> gltfpack: Implement support for KHR_materials_diffuse_transmission

- Makefile
- demo/main.cpp
- demo/tests.cpp
- js/benchmark.js
- src/vertexcodec.cpp
- tools/codecbench.cpp
- tools/codectest.cpp
This PR prototypes initial support for the next vertex codec version.
The change introduces version 0xe; this version has zero compatibility guarantees, and will be in the state of flux wrt bitstream format until it is finalized as version 1. The goals for the next version are to retain comparable decoding performance to v0 -- currently v0 decodes around 4.5 GB/s on Zen 4 (7950X), around 3.5 GB/s on M2 (base) -- and to increase compression ratio, targeting up to ~10% relative improvement on average for a set of geometry data. This will make the decoder more complicated and larger, but hopefully not dramatically so. Some performance loss is probably unavoidable, hopefully it can be kept at ~5% or so.
In this PR the initial infrastructure (version selection, enhanced codectest harness) is …
> vertexcodec: Initial implementation of experimental next version

- demo/main.cpp
- src/vertexcodec.cpp
- tools/codecbench.cpp
- Add control mode stats to trace output; it helps understand the data distribution and mode usefulness
- Make it possible to run codecbench on a set of files; this presents a more accurate picture of decoding performance by running it on non-synthetic data
- Since codecbench can now be used for benchmarking, remove benchmarking code from demo to keep it cleaner
> vertexcodec: Improve tracing and benchmarking tools

- gltf/gltfpack.cpp
Semantically these are exactly the same - JSON output is unordered. However, when inspecting the files manually, it makes more sense to see assets/extensions first. We could append buffers at the end, but we try to follow logical order wrt referencing glTF objects earlier in the JSON stream just in case streaming parsers want to take the opportunity to optimize the parsing flow.
> gltfpack: Output buffers[] list after extension list

- gltf/animation.cpp
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/stream.cpp
- gltf/write.cpp
Using `-af 0` now disables resampling and keeps the original time values.
When resampling is disabled, we can still mark tracks as constant and
remove them if they are not necessary, which cuts down on the animation
size. In this mode it is more difficult to support ranges, so we assume track
range will cover the relevant timespan if any tracks with time survive.
Doing this analysis for cubic splines is slightly more difficult as if
tangents are non-zero, an otherwise "constant" track will not result in
constant output, so we disable analysis in that case for simplicity.
Fixes #815.
> gltfpack: Disable animation resampling when frequency is 0

- .github/workflows/build.yml
- demo/main.cpp
- demo/tests.cpp
- src/vertexcodec.cpp
- tools/codectest.cpp
When using new format we can now select between byte and halfword
deltas, or switch to xor without zigzag encoding (which is
width-invariant).
Different types of deltas are optimal for different content; 2-byte
deltas provide the most value, whereas 4-byte and XOR deltas are more
experimental. This PR initially contained support for 4-byte deltas as well,
but it was increasing complexity without providing value so it was removed.
Xor deltas could be used to optimize for decoding performance when they
don't change the ratio.
The delta encoding is stored as a channel type for every 4 bytes of the
vertex;for now we only need to encode a 2-bit value, but we reserve a full
byte for simplicity - this may change in the future to accommodate rotates.
While varying the channel data per vertex …
> vertexcodec: Implement enhanced delta encoding

- Makefile
- src/vertexcodec.cpp
8-bit unzigzag can be ran before or after transpose; running this after
transpose makes it a little easier for compiler to schedule work given
that transpose needs 8 registers.
More importantly, 16-bit unzigzag ran after transpose has direct access
to unpacked 16-bit data and can avoid doing operations across individual
bytes; this makes decoding ~4% faster.
Also clean up trace output to make it easier to read in shorter views.
> vertexcodec: Decoding performance tuning

- demo/main.cpp
- demo/tests.cpp
- src/vertexcodec.cpp
This can be useful to align the bits better in certain cases. However,
rotates come with a set of questions: what's the granularity? which
delta modes do they work in? how much do they cost to decode?
Ideally perhaps we would do fully orthogonal rotates. However, rotates
can be done as a filter step; as such, from the decoder perspective it's
best to focus on rotate applications that are minimal.
When combined with SUB deltas, rotates must be done after deltas get
recombined. This makes them expensive, as this step is ~scalarized. When
using XOR deltas, rotates can be done before or after undelta; that
makes them cheaper and aligns XOR decoding with other delta forms, as
the cost is similar to unzigzag.
Conceptually, there's also some value in this split: SUB deltas assume
integer-like …
> vertexcodec: Augment XOR delta encoding with rotation

- demo/main.cpp
- demo/tests.cpp
- src/meshoptimizer.h
- src/vertexcodec.cpp
- tools/codecfuzz.cpp
- tools/codectest.cpp
While individual components of the encoder can always be optimized
further, to ensure that control over encode time/size tradeoff is still
present, meshopt_encodeVertexBufferLevel can now choose compression
level. For v0 all levels are equivalent; for v1, currently:
- level 0 is closest to v0 and picks a single bitgroup layout (while
still supporting zero channels as these are fast to reject)
- level 1 picks the best bitgroup layout but only uses byte deltas
- level 2 selects 1- or 2- byte deltas per channel, without XOR/rot
- level 3 selects XOR/rot per channel
These may change as performance characteristics of the encoder change.
This PR also significantly optimizes all levels in subsequent commits.
The initial numbers after the first commit were:
> v0: 0.585 GB/s
> v1 level 0: 0.548 …
> vertexcodec: Implement support for compression levels

- src/vertexcodec.cpp
The second half of the delta decoding loop relies on 16 serialized instructions that
incrementally compute 4 prefix sums and store the results. On Apple CPUs, this is a critical
path of the loop: subsequent iterations depend on updated value of `pi`, and this restricts
throughput.
While this could be worked around by doing parallel prefix sum computations (for each
of the 4 channels individually), that only really works for byte groups. A partial parallel
prefix sum that computes prefix sums in groups of 4 values and then adjusts them with
serial accumulation was implemented in the first commit in this PR; that makes full decoding
~20% faster on Apple M2.
Unfortunately, that approach does not translate to any other CPU - it's slower on Zen 3 and
Graviton 2 - and requires a completely …
> vertexcodec: Additional latency optimizations for delta decoding

- Makefile
- demo/nanite.cpp
While the higher level goal for the demo is to get to a point where METIS is not necessary, this requires ability to carefully evaluate the DAG quality between modes, and a solid baseline. This change fixes a few issues around the latter when METIS is used, specifically:
- Instead of a build-time configuration, we link to METIS dynamically; this makes it easier to work on this code as switching modes never requires a rebuild
- As an extra option, mostly-non-recursive clusterization is added; this is similar to what Bevy added recently, and uses a single partitioning call to get all clusters, and then splits occasional outlier clusters that are larger than the limit. To reduce the splits METIS is instructed to produce smaller clusters - even with a small slop, occasionally much larger …
> demo: Streamline METIS integration in clustered simplification demo

- .github/workflows/build.yml
- .github/workflows/cifuzz.yml
This should be available as of today: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
Coincidentally this also would have prevented #833 (not that this option existed until today!)
> Add Ubuntu ARM runner for build CI

- demo/tests.cpp
- src/clusterizer.cpp
When clusterizer is used to generate meshlets for a small subset of the
mesh, the bulk of the work is in O(vertex_count) loops inside adjacency
build as opposed to the actual clusterizer. Normally the mesh has more
indices than vertices, but for mesh subsets this relationship may be
reversed. This change implements automatic sparse update for adjacency,
which only fills the subset of the adjacency data used by the index buffer.
When using 64 triangle clusters on a 1M triangle mesh, this makes the
clusterization itself ~2x faster, and the hierarchical clustering
process can be ~25% faster as a result.
Additionally, this change also removes the redundant `live_triangles` buffer -
it is the same data as `adjacency.counts` and is always updated in sync, so
we can simply reuse the existing …
> clusterizer: Improve performance and memory use of meshlet builder

- demo/main.cpp
- demo/nanite.cpp
We now analyze connectivity, vertex transform and boundary size for all clusters and output summary statistics per level of detail (DAG depth). This allows more granular analysis and comparison of various algorithms and tweaks.
With these it's more clear that Metis non-recursive clusterization is generally better than the recursive variant, so this change also removes the recursive variant for simplicity.
Note that for now, the code that computes metrics (and is thus non-operational) is intermixed with the code that computes the actual DAG. Since for now this demo is not intended as production-ready example, this is fine but the demo will need to be reworked in the future to serve as a good example.
> demo: Implement various metrics for hierarchical simplification

- src/meshoptimizer.h
`meshopt_quantizeHalf/Float` were initially inline C++ functions but were later converted to proper functions in `quantization.cpp`; however, they were still in the "inline C++" block that was not under `extern "C"`. This makes it harder to access these functions via FFI, so this change moves them, as well as `meshopt_dequantizeHalf`, into `extern "C"` block which changes the function mangling to C.
`meshopt_quantizeUnorm/Snorm` remain inline; this is necessary both for performance, as inlining them with a constant `N` produces much more efficient code, and because they are used in some meshopt algorithm implementations, and by convention every translation unit in meshoptimizer library must be self-contained for ease of compilation.
See …
> Make meshopt_quantizeHalf/Float extern "C"

- CMakeLists.txt
- demo/main.cpp
- demo/nanite.cpp
- demo/tests.cpp
- src/meshoptimizer.h
- src/partition.cpp
This change introduces a new experimental algorithm,
`meshopt_partitionClusters`, which partitions the input clusters into
groups of approximately equal sizes, grouping neighboring clusters using
implied vertex-based adjacency and prioritizing groups that reduce
boundary vertices. This is intended as a replacement to METIS cluster
partitioning for hierarchical simplification pipelines.
The input to the algorithm is an index buffer for each cluster; the adjacency
is automatically inferred from this data. For best results on meshes with
vertex splits it's recommended to supply position-welded ("shadow") indices,
which can be generated via `meshopt_generateShadowIndexBuffer` on the
array before partitioning (see `main.cpp`/`simplifyClusters` example), or by
manually remapping the indices …
> Experimental cluster partitioning

- demo/nanite.cpp
- src/meshoptimizer.h
- src/partition.cpp
This is a small followup to the previous PR, which adjusts the metric used for merging to normalize the shared counts with respect to the expected group boundary, which in practice works similarly to the group size bias but is more principled, and slightly lowers the max partition size. The previous PR focused a little too much on reducing the boundary, and as a result the average partition size was a little higher than the target; slightly reducing the acceptable partition size makes this better, especially when the target is a power of two (as it blocks the "natural" way to get to 3/2*2^k by repeated doubling until the last merge).
Some other metrics were evaluated for merging heuristic; there's a few other interesting candidates, for example "mulrsqrt" (which replaces `+` in this PR by …
> Improve partitioning scoring and group size limits

- demo/nanite.cpp
This change mostly refactors the code to be easier to understand and follow:
- All metrics computations are centralized in a separate function so that it doesn't obscure the processing flow
- All metrics and METIS related implementations moved to the end of the file
- Remove some redundant statistics and fix some metrics that were off between levels
Also remove single cluster special case. In general, it's not clear that it needs to be special-cased, as a group with merged disconnected clusters is just effectively synchronizing the LOD transition decisions between different clusters; but for now since meshopt partitioning leaves these alone, this helps reduce the overall triangle count a bit further for some meshes.
> demo: Hierarchical simplification cleanup/refactoring

- demo/main.cpp
- demo/nanite.cpp
- demo/tests.cpp
- src/clusterizer.cpp
- src/meshoptimizer.h
In some cases, producing clusters from two disconnected regions of the
mesh may result in efficiency loss in the downstream algorithms; this is
sometimes hard to avoid due to unpredictable traversal flow. This change
introduces a variant of the existing meshlet builder,
`meshopt_buildMeshletsFlex`, which has two triangle count limits: a lower
and upper limit. When a cluster is below a lower limit, the logic
remains the same, however for larger clusters we allow splitting the
resulting cluster if not doing that would result in excessively large
volume, as measured by `split_factor`.
For now, `split_factor` is applied to the expected radius to serve as a
cutoff value; this assumes somewhat uniform input triangle sizes, but
also protects against clusters that are already disjointly merged …
> clusterizer: Add buildMeshletsFlex with flexible cluster sizing

- gltf/stream.cpp
When float quantization is not used, we use the same quantization
settings for all meshes. This simplifies the flow as skins and materials
may need to change based on the quantization grid, and in some cases
eliminates micro gaps between meshes, but may result in reduced
precision compared to using per-mesh grids.
For now we detect this case and suggest increasing the number of bits
used for positions or switching to floating-point quantization.
One other possible option that can improve this is `-kn` but this is more
situational so for now the warning message doesn't recommend it.
Closes #433
> gltfpack: Warn when position quantization error is significant

- demo/nanite.cpp
- demo/tests.cpp
- src/clusterizer.cpp
- src/meshoptimizer.h
The existing functions for computing cluster bounds,
`meshopt_computeMeshletBounds` and `meshopt_computeClusterBounds`, rely on
an internal algorithm to compute bounding spheres. This algorithm can be
useful in a few other cases:
- The cluster functions limit the input size to avoid allocations, as
they need to reshape the inputs into a form that can be consumed by
the internal function; sometimes it's convenient to compute a bounding
sphere of what is essentially an unbounded point cloud
- For hierarchical simplification, it's useful to be able to compute a
bounding sphere for an input set of spheres instead of just points.
This change exposes a basic implementation of both of the above with one
(experimental) function that takes a set of points and, optionally, a per-point radius: …
> clusterizer: Expose sphere bounds computation

- demo/tests.cpp
- src/indexcodec.cpp
- tools/codecbench.cpp
This change mostly intends to break a compiler "optimization" that ends
up slowing this code, which merges tails of all 4 blocks as all 4 of
them have two pushEdgeFifo calls that look the same. In addition to a
less efficient control flow, on MSVC in particular this seems to break
several codegen optimizations, which also results in locally suboptimal
code, such as using `imul` to compute the store address for edgefifo.
Since writeTriangle always has a branch, it's actually more efficient to
place it to the end of the block anyway as it results in a more
streamlined control flow, and this also happens to make the structure
different enough from the remaining two blocks that tail merging doesn't
happen.
This makes MSVC decoding ~8% faster.
> indexcodec: Restructure decoding fast path for better codegen

- src/simplifier.cpp
Before this change, if two vertices had positions that only differ in the sign of zero in one of the components, the vertices would be treated as separate.
This could lead to some seam vertices being classified as two border vertices instead, which then allowed the simplifier to pull them in two different directions, creating a small gap.
To fix this, we need to make sure negative zero hashes to 0, and the positions are compared using floating point equality instead of bitwise equality. If any vertices have NaN components, this will lead to them not being merged into one, but these are going to produce NaN quadrics anyway which will effectively lock simplification in the neighborhood regardless of topology.
> simplifier: Adjust position hasher to handle negative zero

- Makefile
- demo/main.cpp
- demo/nanite.cpp
- src/clusterizer.cpp
- src/meshoptimizer.h
- tools/clusterfuzz.cpp
In order to improve performance of clusters used for raytracing, we need
to generate clusters in a SAH optimal manner; the best approach seems to
be to build a BVH and extract subtrees into clusters.
This change implements the initial version of this algorithm; for now, the
control over the cluster sizes is a little too strict (clusters will be
generated in multiples of `min_triangles` triangles which is not strictly
required; that results in reduction of SAH quality).
No attempt to control for cluster overlap or underfill is made atm; this will
be improved in subsequent PRs and may require additional parameters to the
function.
The name is also potentially temporary; I'm not sure that `buildMeshletsSplit`
will be the final name. All of these details will stabilize before any versioned …
> clusterizer: Implement experimental BVH clusterizer

- demo/tests.cpp
- src/clusterizer.cpp
For the new experimental clusterizer introduced in #871, when
`min_triangles < max_triangles`, we used to step in units of
`min_triangles` which resulted in much fewer valid splits being
evaluated.
While we need to restrict the splits to conform to `min..max` range, what
we actually need here is to check if the split sequence can be
representable as a sum of numbers between `min` and `max`. When the initial
sequence is divisible like that, we'd like both splits to be; otherwise
we opt for just one being representable.
This change also improves the vertex bound splits as a byproduct:
instead of forcing an even split in `count/3` chunks, our splits are more
adaptive and as such more likely to produce higher quality SAH nodes.
Additionally, this change fixes some corner cases when degenerate …
> clusterizer: Improve cluster sizing criteria for min<max

- demo/main.cpp
- demo/nanite.cpp
- demo/tests.cpp
- src/clusterizer.cpp
- src/meshoptimizer.h
- tools/clusterfuzz.cpp
When using min..max ranges, we now can optionally adjust the split
weights to increase the cost according to the unevenness of the split;
splits that divide clusters into max_triangles multiples do not change
their costs.
Increasing the fill weight effectively increases the SAH cost along with
increasing the cluster fill, making it easier to tune the subdivision
compared to using a fixed minimum triangle number.
When clusters are vertex bound, this alignment breaks SAH optimality too
much and results in suboptimal splits so we disable it.
Additionally, this change switches to bounding box centroids for sorting.
This matches commonly used HW implementations better and results in
cleaner boundaries between triangles on regular grids as triangles that
are part of the same quad are more …
> clusterizer: Improve cluster fill and splitting criteria

- README.md
- demo/main.cpp
- demo/tests.cpp
- src/meshoptimizer.h
- src/vertexcodec.cpp
- tools/codecfuzz.cpp
- tools/codectest.cpp
Instead of relying strictly on the global version set via `meshopt_encodeVertexVersion`, specify the version override as an extra argument to `meshopt_encodeVertexBufferLevel`. When set to -1, this maintains the current behavior, but it can be set to 0/1 explicitly.
This unlocks encoding multiple streams with different versions concurrently; it's also somewhat sensible to bundle these two because when version is 0, the level argument does not do anything. This API should be forward compatible in that if vertex codec v2 ever appears, the same approach should continue working.
Note that this is specific to vertex encoding. Index encoding currently does not have a v2, and v0 is effectively already legacy; so a separate function does not seem warranted for now. If index codec v2 is introduced …
> vertexcodec: Add version argument to encodeVertexBufferLevel

- README.md
- demo/tests.cpp
- src/meshoptimizer.h
- src/simplifier.cpp
When simplifying meshes, SimplifyPrune flag is useful to be able to
discard connected components that are below the currently tracked error.
In some cases, this gives insufficient control over the result. Notably,
it might be desirable to remove components below an acceptable size
cutoff which is larger than the simplification error; additionally, it
can be useful to remove components *without* doing any other types of
simplification - this can be used for mesh cleanup, especially after
isosurface extraction.
This change exposes the existing component pruning functionality using a
separate explicit function call, in addition to the simplification flag.
> simplifier: Add experimental simplifyPrune function

- extern/cgltf.h
- gltf/parsegltf.cpp
If the index buffer is much smaller than vertex accessors, and vertex accessors
are shared, we end up re-unpacking the accessors repeatedly and producing huge
meshes that are inefficient for the rest of the processing pipeline.
This change detects these cases and switches to reading the individual elements
according to the index buffer, producing an unindexed mesh; the rest of the
processing will re-index it again.
For some extreme cases this may result in significant improvements in parsing and
processing time; the mesh from #884 could not be converted before this change,
and with this change it takes just 0.3s to do so.
Before settling on the approach here, I've also tried trimming the index buffers to
their min..max range and extracting an associated subrange from the accessors;
this …
> gltfpack: Deindex meshes with abnormally large vertex accessors

- demo/main.cpp
- src/meshoptimizer.h
- src/spatialorder.cpp
Instead of a global Morton sort, we use hierarchical axis subdivision that ensures that all splits are aligned to a given boundary, leaving leaves unsorted. This is a good fit when the resulting point cloud needs to be processed in parallel, similarly to meshlets. Compared to Morton sort followed by a naive bucketed split, this results in consistently smaller bounds at some extra processing cost.
Unlike spatialSortRemap, this generates an index buffer - not a remap table. Naturally, a new set of points can be constructed without the use of indexing.
This PR also optimizes spatialSort* functions to reduce cache pressure on large meshes.
Fixes #642.
> spatialorder: Introduce experimental point clusterizer

- CMakeLists.txt
- src/allocator.cpp
- src/meshoptimizer.h
Using templated class static allowed us to avoid function calls even in
unoptimized builds, but results in conflicts with Clang's C++20 module
implementation when meshoptimizer.h is included in global module
fragment. Instead, we now use a function static to store this state and
require a function call to get access to it.
Additionally, while allocator callbacks were deduplicated by the linker
within an individual module, when meshoptimizer was compiled as a
shared library the library code and the calling code would get
separate configuration, and allocator overrides would not affect temporary
allocations done by meshopt_IndexAdapter. To fix that, this PR introduces
a separate configuration option, `MESHOPTIMIZER_ALLOC_EXPORT`,
which can be used to declare the allocator storage function …
> Rework meshopt_Allocator callback storage

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
Instead of using the same target error for each mesh, we now use a factor derived from the ratio of mesh extent to the largest mesh extent to ensure that meshes of different sizes get roughly the same visual degradation.
When meshes are instanced, we take the largest possible scale as a factor; smaller instances will retain more detail.
While we could use the ratio of mesh bounds to scene bounds instead of a ratio to max mesh bounds, there's cases where the input is a collection of objects that are intended to be moved around in space, and the scene bounds is not necessarily representative. With this the simplification behavior is roughly similar to quantization behavior (modulo scale treatment).
Note that we still use the same ratio to simplify every mesh in isolation; this doesn't …
> gltfpack: Scale simplification error with mesh extents

- src/overdrawoptimizer.cpp
Instead of iterating through indices when computing mesh centroid, iterate through vertices. This results in averaging a mostly deduplicated set of positions, which produces a slightly different result but the overall overdraw results are within margin of error on a large mesh set.
However, this results in much faster computation of the centroid itself as we need to process fewer points and do so with linear memory access, so this makes optimizeOverdraw ~15% faster overall on typical meshes.
> overdraw: Compute mesh centroid using vertex data

- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/material.cpp
- gltf/mesh.cpp
If mesh has a vertex color stream with some transparent colors, we can't
change material blending mode, as both MASK and BLEND will affect
rendering behavior. This requires an extra analysis step before we
optimize materials.
Fixes #909.
>  gltfpack: Preserve material alpha mode for meshes with vertex alpha

- src/simplifier.cpp
In complex meshes it's possible to encounter a somewhat unusual type of vertex: one that only has a single copy (wedge), and that has one incoming and one outgoing open edge, but both edges connect to vertices with the same position.
Previously, we classified vertices like this as border, because border classification ignored this possibility. This created cases where a border vertex is adjacent to a seam vertex, but neither can be collapsed onto each other because of collapse restrictions.
Doing the right thing here is somewhat complicated. Locking vertices like this to avoid misleading classification regresses cases where a half-seam vertex like this is connected to a locked vertex; these are the cases that in theory may lead to issues on discontinuities but in practice we don't seem to …
> simplifier: Classify half-seams as seams instead of borders

- .github/workflows/build.yml
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/stream.cpp
- gltf/write.cpp
When a new command line argument `-vi` is used, gltfpack now produces
interleaved vertex streams instead of deinterleaving per attribute. This
can be helpful for some native renderers and may improve rendering
efficiency on some GPUs.
Interleaving is not compatible with vertex filters, so they are disabled
in this mode. This reduces compression efficiency when options like `-cc`
or `-vpf` together with `-c` are used. Filters can still be used on
animation data.
When the mesh is using morph targets, each morph target is interleaved
separately. This prevents vertices from having very large strides on
meshes with many targets, and results in more efficient access patterns
if a small subset of morph targets is used at runtime.
Fixes #924.
> gltfpack: Implement support for interleaved vertices

- .github/workflows/build.yml
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
Using `-sp` now enables permissive simplification, which allows the
simplifier to simplify across normal discontinuities; UV discontinuities
are protected and should simplify similarly to how the regular mode
works.
This is meant as an alternative to aggressive mode, which is using
sloppy simplification as a fallback. Sloppy simplification doesn't
preserve attributes and doesn't support attribute weighting, and has
issues with volume and shape conservation.
Permissive mode has quality limitations and is not always maximally
effective; this will be improved in the future.
> gltfpack: Introduce an option for permissive simplification

- README.md
- demo/main.cpp
- demo/nanite.cpp
- demo/tests.cpp
- src/clusterizer.cpp
- src/meshoptimizer.h
The original idea has been to change the heuristic to produce higher
quality splits for raytracing focused workflows. Unfortunately, this
doesn't *really* work: the impact on RT efficiency is, on average, net
negative, and in general this doesn't solve the problem very well even
for meshes where it is an improvement. Since a new algorithm,
buildMeshletsSpatial, solves that use case much better, we don't need
this feature anymore.
Since buildMeshletsFlex is experimental, this can be done without
additional versioning. If we need some sort of adjustment like this in
the future, we can still use negative cone_weight as a flag, it's just
that this specific heuristic does not work very well.
While buildMeshletsFlex itself is still useful as it provides better control
over spatial locality, and …
> clusterizer: Remove negative cone_weight from buildMeshletsFlex

- gltf/gltfpack.cpp
This PR to solve #943  adds an early validation of the output filename extension in gltfpack(). 
If -o is provided and the extension isn’t .gltf or .glb, the tool now exits immediately with the same non-zero code used by the current late check. 
This avoids:
- running the full processing pipeline on an output that will be rejected,
- encoding/copying textures into the target directory,
- confusing partial side-effects followed by a late error.
Tests (-test) that call gltfpack(path, NULL, …) continue to work as before. 
Fixes #943.
> Validate output extension up front to prevent late failure and unnecessary work

- src/clusterizer.cpp
On meshes with many topologically disjoint clusters, kdtreeNearest
spends an increasing amount of time going over already emitted
triangles. To fix this, we can detect leaves that have all triangles
already emitted and flag them as inactive using children=0. This, then,
can be propagated to branch nodes using children=0 as a flag as well.
For branches, we do this *before* visiting either node. This makes
deactivation lazier than it strictly speaking needs to be, but it keeps
the existing recursive traversal structure where the second call is a
tail call, which on some models results in extra speedup.
Overall, while on some meshes this is neutral because the KD tree search
is used rarely, on meshes with more seams this can improve the meshlet
building time anywhere from 15% to 40%:
Mesh | …
>  clusterizer: Iteratively cut KD branches to speed up traversal

- README.md
- demo/main.cpp
- demo/nanite.cpp
- demo/tests.cpp
- js/meshopt_clusterizer.js
- js/meshopt_clusterizer.module.js
- src/clusterizer.cpp
- src/meshoptimizer.h
`meshopt_buildMeshlets` used to pad meshlet indices to a 4b boundary.
This padding was initially motivated by the original `NV_mesh_shader`
extension and its intrinsic, `writePackedPrimitiveIndices4x8NV`, that
could be used to more efficiently submit data to the rasterizer.
This decision led to multiple paper-cuts in the API; notably, due to
buffer sizing requirements, this led to restricting min/max triangle
limits to be divisible by 4, conflicting with NVidia recommendation to
use 126 triangle meshlets, and creating further problems for newer Flex
and Spatial API variants where min_triangles establishes the actual
limits and needs to also be aligned.
Additionally, while `NV_mesh_shader` extension with the packed intrinsic
is still available, the packed intrinsic does not seem to be …
>  clusterizer: Remove 4b alignment padding and alignment requirements

- README.md
- demo/main.cpp
- js/README.md
- js/meshopt_encoder.js
- js/meshopt_encoder.module.d.ts
- js/meshopt_encoder.module.js
- js/meshopt_encoder.test.js
- src/meshoptimizer.h
- src/vertexcodec.cpp
- tools/codecbench.cpp
- tools/codectest.cpp
`meshopt_encodeVertexBuffer` will now produce v1 streams instead of v0.
This can be overridden using `meshopt_encodeVertexVersion(0)` or by
passing `version=0` to `meshopt_encodeVertexBufferLevel`.
There should not be any reasons to use version 0 format other than for
compatibility with older builds of the applications that predate v1
support, or for glTF encoding. Applications that encode data for glTF
extension `EXT_meshopt_compression` should use one of the above methods
for changing the version to 0.
For JavaScript MeshoptEncoder interface, similarly, `encodeVertexBuffer*` now
default to version 1. The existing function `MeshoptEncoder.encodeGltfBuffer`
still encodes version 0 by default, but gains a `version` parameter to make it easy
to switch to version 1 - assuming this gets added …
>  vertexcodec: Encode using vertex version 1 by default

- gltf/README.md
- gltf/gltfpack.cpp
- gltf/gltfpack.h
- gltf/mesh.cpp
- gltf/parsegltf.cpp
- gltf/write.cpp
This change extracts unrelated commits from #950, so that that PR can be smaller. This also documents handling of custom glTF data that's not covered by extensions.
> gltfpack: Refactor instance data handling

- src/simplifier.cpp
In some rare cases of extremely large meshes, e.g. 90M vertices, even setting a bit per vertex can limit simplification throughput considerably when simplifying individual clusters in a larger subdivision.
There is no need to zero out the entire array: we can instead just clear the bit groups that are referenced by the indices. This should not change the performance of sparse simplification in general, as the bit setting loop is more expensive than a sparse clear.
The uncached allocation of a large bit array may still be an issue as we'd need to pagefault on the indices that *are* referenced - however, this can be fixed by the caller by providing a per-thread arena that's sufficiently large to accomodate the bitset.
> simplifier: Improve performance of SimplifySparse on very sparse subsets

- demo/nanite.cpp
This change cleans up the clustered LOD builder example. Some extraneous prototype code, including METIS dependency, was removed, all configuration variables got extracted into top level constants, permissive simplification can now be used as a default mode (without fallback), and sloppy simplification fallback has been significantly improved wrt performance so that it's practical to keep enabled, which ensures clean DAGs for most meshes.
This was originally part of a more ambitious rework (https://github.com/zeux/meshoptimizer/pull/954) which included a standalone generic C interface to this functionality with separate position/attribute streams and access to DAG results without having to change the implementation; however, this was probably a step too far, as the actual implementation …
> demo: Improve clustered LOD example code

- README.md
- js/meshopt_simplifier.module.d.ts
- src/meshoptimizer.h
After the addition of vertex locks, no further changes are planned to
the interface (or implementation) of the algorithm; further improvements
are likely to be concentrated in the main simplification algorithm
family instead.
Recently updated clustered LOD example (#956) demonstrates how to use
sloppy simplifier for sparse subsets, so this doesn't need to be part of the
algorithm itself. 
As part of this, add a templated overload for the version with
vertex_lock; when vertex_lock was added, the existing templated overload
was kept to provide source level compatibility, but for consistency we
also need a generic version for the full parameter set.
>  simplifier: Mark meshopt_simplifySloppy as stable

- demo/clusterlod.h
- demo/main.cpp
- demo/nanite.cpp
- src/partition.cpp
- src/simplifier.cpp
> This is a followup to #956 and a replacement of #954.
This change significantly reworks the clustered LOD builder example. The actual implementation is mostly identical in the flow, however it's structured to be easier to start with or reuse when implementing a system like Nanite - it exposes a proper C interface with a generalized input mesh, returns the output cluster group data via callbacks, and exposes a lot of configuration knobs to control the process.
For simplicity, this does *not* include a glTF sample but [clodgltf.cpp](https://github.com/zeux/meshoptimizer/blob/7dfe4cc7553f1ee2d4789fd931130c5aec2afda2/tools/clodgltf.cpp) from the linked PR can be used more or less as is; when ran on NVidia Zorah sample scene (~1.7B triangles) it generates a full DAG for every mesh, and the …
> demo: Rework clustered LOD code

- demo/clusterlod.h
- Fix under-reservation for merged indices that would cause us to reallocate once or twice
- Use faster `lockBoundary` implementation that does not need an extra large temporary array
> demo: Reduce allocation pressure in clustered LOD
